In [1]:
#1
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [2]:
#2
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print(df.shape)

(10683, 11)

In [4]:
#3
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print(df.columns)

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [7]:
#4
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print(df.dtypes)

Airline              str
Date_of_Journey      str
Source               str
Destination          str
Route                str
Dep_Time             str
Arrival_Time         str
Duration             str
Total_Stops          str
Additional_Info      str
Price              int64
dtype: object

In [1]:
#5
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [2]:
#6
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [3]:
#7
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
missing_percentage = df.isnull().mean()*100
print("Percentage of missing values:")
print(missing_percentage)

Percentage of missing values:
Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

In [4]:
#8
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print("Unique Values:")
print(df["Airline"].nunique())
print("\nFrequency of each value:")
print(df["Airline"].value_counts())

Unique Values:
12

Frequency of each value:
Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [6]:
#9
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print("Frequency distribution of total stops:")
print(df["Total_Stops"].value_counts(dropna=False))

Frequency distribution of total stops:
Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

In [14]:
#10
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format = "%d/%M/%Y")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,2019-01-24 00:03:00,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,2019-01-01 00:05:00,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,2019-01-09 00:06:00,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,2019-01-12 00:05:00,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,2019-01-01 00:03:00,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-01-09 00:04:00,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,2019-01-27 00:04:00,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,2019-01-27 00:04:00,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,2019-01-01 00:03:00,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,2019-01-09 00:05:00,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [26]:
#11
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Date of journey date:")
df["Day"] = df["Date_of_Journey"].dt.day
df[["Date_of_Journey","Day"]].head()

Date of journey date:

  Date_of_Journey  Day
0      2019-03-24   24
1      2019-05-01    1
2      2019-06-09    9
3      2019-05-12   12
4      2019-03-01    1

In [25]:
#12
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Date of Journey Month")
df["Month"] = df["Date_of_Journey"].dt.month
df[["Date_of_Journey","Month"]].head(10)

Date of Journey Month

  Date_of_Journey  Month
0      2019-03-24      3
1      2019-05-01      5
2      2019-06-09      6
3      2019-05-12      5
4      2019-03-01      3
5      2019-06-24      6
6      2019-03-12      3
7      2019-03-01      3
8      2019-03-12      3
9      2019-05-27      5

In [30]:
#13
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Date of journey Year:")
df["Year"] = df["Date_of_Journey"].dt.year
df[["Date_of_Journey","Year"]].head(10)

Date of journey Year:

  Date_of_Journey  Year
0      2019-03-24  2019
1      2019-05-01  2019
2      2019-06-09  2019
3      2019-05-12  2019
4      2019-03-01  2019
5      2019-06-24  2019
6      2019-03-12  2019
7      2019-03-01  2019
8      2019-03-12  2019
9      2019-05-27  2019

In [ ]:
#14
import pandas as pd
df