In [1]:
#1
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [2]:
#2
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print(df.shape)

(10683, 11)

In [4]:
#3
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print(df.columns)

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [7]:
#4
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print(df.dtypes)

Airline              str
Date_of_Journey      str
Source               str
Destination          str
Route                str
Dep_Time             str
Arrival_Time         str
Duration             str
Total_Stops          str
Additional_Info      str
Price              int64
dtype: object

In [1]:
#5
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [2]:
#6
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [3]:
#7
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
missing_percentage = df.isnull().mean()*100
print("Percentage of missing values:")
print(missing_percentage)

Percentage of missing values:
Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

In [4]:
#8
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print("Unique Values:")
print(df["Airline"].nunique())
print("\nFrequency of each value:")
print(df["Airline"].value_counts())

Unique Values:
12

Frequency of each value:
Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [6]:
#9
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
print("Frequency distribution of total stops:")
print(df["Total_Stops"].value_counts(dropna=False))

Frequency distribution of total stops:
Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64

In [14]:
#10
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format = "%d/%M/%Y")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,2019-01-24 00:03:00,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,2019-01-01 00:05:00,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,2019-01-09 00:06:00,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,2019-01-12 00:05:00,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,2019-01-01 00:03:00,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-01-09 00:04:00,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,2019-01-27 00:04:00,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,2019-01-27 00:04:00,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,2019-01-01 00:03:00,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,2019-01-09 00:05:00,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [26]:
#11
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Date of journey date:")
df["Day"] = df["Date_of_Journey"].dt.day
df[["Date_of_Journey","Day"]].head()

Date of journey date:

  Date_of_Journey  Day
0      2019-03-24   24
1      2019-05-01    1
2      2019-06-09    9
3      2019-05-12   12
4      2019-03-01    1

In [25]:
#12
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Date of Journey Month")
df["Month"] = df["Date_of_Journey"].dt.month
df[["Date_of_Journey","Month"]].head(10)

Date of Journey Month

  Date_of_Journey  Month
0      2019-03-24      3
1      2019-05-01      5
2      2019-06-09      6
3      2019-05-12      5
4      2019-03-01      3
5      2019-06-24      6
6      2019-03-12      3
7      2019-03-01      3
8      2019-03-12      3
9      2019-05-27      5

In [30]:
#13
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Date of journey Year:")
df["Year"] = df["Date_of_Journey"].dt.year
df[["Date_of_Journey","Year"]].head(10)

Date of journey Year:

  Date_of_Journey  Year
0      2019-03-24  2019
1      2019-05-01  2019
2      2019-06-09  2019
3      2019-05-12  2019
4      2019-03-01  2019
5      2019-06-24  2019
6      2019-03-12  2019
7      2019-03-01  2019
8      2019-03-12  2019
9      2019-05-27  2019

In [10]:
#14
import pandas as pd
from IPython.display import display
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],format="%d/%m/%Y")
print("Day of journey date:")
df["Day"] = df["Date_of_Journey"].dt.day
display(df[["Date_of_Journey","Day"]])
print("\nMonth of journey date:")
df["Month"] = df["Date_of_Journey"].dt.month
display(df[["Date_of_Journey","Month"]])
print("\nYear of Journey date:")
df["Year"] = df["Date_of_Journey"].dt.year
display(df[["Date_of_Journey","Year"]])
print("\nOriginal Date of Journey")
display(df[["Date_of_Journey"]])

Day of journey date:

      Date_of_Journey  Day
0          2019-03-24   24
1          2019-05-01    1
2          2019-06-09    9
3          2019-05-12   12
4          2019-03-01    1
...               ...  ...
10678      2019-04-09    9
10679      2019-04-27   27
10680      2019-04-27   27
10681      2019-03-01    1
10682      2019-05-09    9

[10683 rows x 2 columns]

Month of journey date:

      Date_of_Journey  Month
0          2019-03-24      3
1          2019-05-01      5
2          2019-06-09      6
3          2019-05-12      5
4          2019-03-01      3
...               ...    ...
10678      2019-04-09      4
10679      2019-04-27      4
10680      2019-04-27      4
10681      2019-03-01      3
10682      2019-05-09      5

[10683 rows x 2 columns]

Year of Journey date:

      Date_of_Journey  Year
0          2019-03-24  2019
1          2019-05-01  2019
2          2019-06-09  2019
3          2019-05-12  2019
4          2019-03-01  2019
...               ...   ...
10678      2019-04-09  2019
10679      2019-04-27  2019
10680      2019-04-27  2019
10681      2019-03-01  2019
10682      2019-05-09  2019

[10683 rows x 2 columns]

Original Date of Journey

      Date_of_Journey
0          2019-03-24
1          2019-05-01
2          2019-06-09
3          2019-05-12
4          2019-03-01
...               ...
10678      2019-04-09
10679      2019-04-27
10680      2019-04-27
10681      2019-03-01
10682      2019-05-09

[10683 rows x 1 columns]

In [11]:
#15
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])
print("Departure hour from dep time:")
df["Dep_Hour"] = df["Dep_Time"].dt.hour
display(df[["Dep_Time","Dep_Hour"]])

Departure hour from dep time:

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\1164212864.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])

                 Dep_Time  Dep_Hour
0     2026-09-27 22:20:00        22
1     2026-09-27 05:50:00         5
2     2026-09-27 09:25:00         9
3     2026-09-27 18:05:00        18
4     2026-09-27 16:50:00        16
...                   ...       ...
10678 2026-09-27 19:55:00        19
10679 2026-09-27 20:45:00        20
10680 2026-09-27 08:20:00         8
10681 2026-09-27 11:30:00        11
10682 2026-09-27 10:55:00        10

[10683 rows x 2 columns]

In [13]:
#16
import pandas as pd
df = pd.read_csv("Data_Train.xlsx - Sheet1.csv")
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])
print("Departure Minute from Dep Hour:")
df["Minute"] = df["Dep_Time"].dt.minute
display(df[["Dep_Time","Minute"]])

Departure Minute from Dep Hour:

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\1845461065.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])

                 Dep_Time  Minute
0     2026-09-27 22:20:00      20
1     2026-09-27 05:50:00      50
2     2026-09-27 09:25:00      25
3     2026-09-27 18:05:00       5
4     2026-09-27 16:50:00      50
...                   ...     ...
10678 2026-09-27 19:55:00      55
10679 2026-09-27 20:45:00      45
10680 2026-09-27 08:20:00      20
10681 2026-09-27 11:30:00      30
10682 2026-09-27 10:55:00      55

[10683 rows x 2 columns]

In [14]:
#17
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])
print("Hour from dep time:")
df["Hour"] = df["Dep_Time"].dt.hour
display(df[["Dep_Time","Hour"]])
print("\nMinute from dep time:")
df["Minute"] = df["Dep_Time"].dt.minute
display(df[["Dep_Time","Minute"]])
print("\nSeconds from dep time:")
df["Second"] = df["Dep_Time"].dt.second
display(df[["Dep_Time","Second"]])
print("\nOriginal Dep Time:")
display(df["Dep_Time"])

Hour from dep time:

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\321328750.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Dep_Time"] = pd.to_datetime(df["Dep_Time"])

                 Dep_Time  Hour
0     2026-09-27 22:20:00    22
1     2026-09-27 05:50:00     5
2     2026-09-27 09:25:00     9
3     2026-09-27 18:05:00    18
4     2026-09-27 16:50:00    16
...                   ...   ...
10678 2026-09-27 19:55:00    19
10679 2026-09-27 20:45:00    20
10680 2026-09-27 08:20:00     8
10681 2026-09-27 11:30:00    11
10682 2026-09-27 10:55:00    10

[10683 rows x 2 columns]

Minute from dep time:

                 Dep_Time  Minute
0     2026-09-27 22:20:00      20
1     2026-09-27 05:50:00      50
2     2026-09-27 09:25:00      25
3     2026-09-27 18:05:00       5
4     2026-09-27 16:50:00      50
...                   ...     ...
10678 2026-09-27 19:55:00      55
10679 2026-09-27 20:45:00      45
10680 2026-09-27 08:20:00      20
10681 2026-09-27 11:30:00      30
10682 2026-09-27 10:55:00      55

[10683 rows x 2 columns]

Seconds from dep time:

                 Dep_Time  Second
0     2026-09-27 22:20:00       0
1     2026-09-27 05:50:00       0
2     2026-09-27 09:25:00       0
3     2026-09-27 18:05:00       0
4     2026-09-27 16:50:00       0
...                   ...     ...
10678 2026-09-27 19:55:00       0
10679 2026-09-27 20:45:00       0
10680 2026-09-27 08:20:00       0
10681 2026-09-27 11:30:00       0
10682 2026-09-27 10:55:00       0

[10683 rows x 2 columns]

Original Dep Time:

0       2026-09-27 22:20:00
1       2026-09-27 05:50:00
2       2026-09-27 09:25:00
3       2026-09-27 18:05:00
4       2026-09-27 16:50:00
                ...
10678   2026-09-27 19:55:00
10679   2026-09-27 20:45:00
10680   2026-09-27 08:20:00
10681   2026-09-27 11:30:00
10682   2026-09-27 10:55:00
Name: Dep_Time, Length: 10683, dtype: datetime64[us]

In [ ]:
#18
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])
print("Time portion from arrival time:")
df["Time"] = df["Arrival_Time"].dt.strftime("%H:%M")
display(df[["Arrival_Time","Time"]])

Time portion from arrival time:

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\1756291613.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])

             Arrival_Time   Time
0     2026-03-22 01:10:00  01:10
1     2026-09-27 13:15:00  13:15
2     2026-06-10 04:25:00  04:25
3     2026-09-27 23:30:00  23:30
4     2026-09-27 21:35:00  21:35
...                   ...    ...
10678 2026-09-27 22:25:00  22:25
10679 2026-09-27 23:20:00  23:20
10680 2026-09-27 11:20:00  11:20
10681 2026-09-27 14:10:00  14:10
10682 2026-09-27 19:15:00  19:15

[10683 rows x 2 columns]

In [18]:
#19
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])
print("Arrival hour from Arrival Time:")
df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
display(df[["Arrival_Time","Arrival_Hour"]])
print("\nArrival Minute from Arrival Time:")
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute
display(df[["Arrival_Time","Arrival_Minute"]])

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\3519319638.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])

Arrival hour from Arrival Time:

             Arrival_Time  Arrival_Hour
0     2026-03-22 01:10:00             1
1     2026-09-27 13:15:00            13
2     2026-06-10 04:25:00             4
3     2026-09-27 23:30:00            23
4     2026-09-27 21:35:00            21
...                   ...           ...
10678 2026-09-27 22:25:00            22
10679 2026-09-27 23:20:00            23
10680 2026-09-27 11:20:00            11
10681 2026-09-27 14:10:00            14
10682 2026-09-27 19:15:00            19

[10683 rows x 2 columns]

Arrival Minute from Arrival Time:

             Arrival_Time  Arrival_Minute
0     2026-03-22 01:10:00              10
1     2026-09-27 13:15:00              15
2     2026-06-10 04:25:00              25
3     2026-09-27 23:30:00              30
4     2026-09-27 21:35:00              35
...                   ...             ...
10678 2026-09-27 22:25:00              25
10679 2026-09-27 23:20:00              20
10680 2026-09-27 11:20:00              20
10681 2026-09-27 14:10:00              10
10682 2026-09-27 19:15:00              15

[10683 rows x 2 columns]

In [19]:
#20
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])
print("Arrival Hour from Arrival Time:")
df["Arrival_Hour"] = df["Arrival_Time"].dt.hour
display(df[["Arrival_Time","Arrival_Hour"]])
print("\nArrival Minute from Arrival Time:")
df["Arrival_Minute"] = df["Arrival_Time"].dt.minute
display(df[["Arrival_Time","Arrival_Minute"]])
print("\nOriginal Arrival Time:")
display(df["Arrival_Time"])

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\1025010451.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"] = pd.to_datetime(df["Arrival_Time"])

Arrival Hour from Arrival Time:

             Arrival_Time  Arrival_Hour
0     2026-03-22 01:10:00             1
1     2026-09-27 13:15:00            13
2     2026-06-10 04:25:00             4
3     2026-09-27 23:30:00            23
4     2026-09-27 21:35:00            21
...                   ...           ...
10678 2026-09-27 22:25:00            22
10679 2026-09-27 23:20:00            23
10680 2026-09-27 11:20:00            11
10681 2026-09-27 14:10:00            14
10682 2026-09-27 19:15:00            19

[10683 rows x 2 columns]

Arrival Minute from Arrival Time:

             Arrival_Time  Arrival_Minute
0     2026-03-22 01:10:00              10
1     2026-09-27 13:15:00              15
2     2026-06-10 04:25:00              25
3     2026-09-27 23:30:00              30
4     2026-09-27 21:35:00              35
...                   ...             ...
10678 2026-09-27 22:25:00              25
10679 2026-09-27 23:20:00              20
10680 2026-09-27 11:20:00              20
10681 2026-09-27 14:10:00              10
10682 2026-09-27 19:15:00              15

[10683 rows x 2 columns]

Original Arrival Time:

0       2026-03-22 01:10:00
1       2026-09-27 13:15:00
2       2026-06-10 04:25:00
3       2026-09-27 23:30:00
4       2026-09-27 21:35:00
                ...
10678   2026-09-27 22:25:00
10679   2026-09-27 23:20:00
10680   2026-09-27 11:20:00
10681   2026-09-27 14:10:00
10682   2026-09-27 19:15:00
Name: Arrival_Time, Length: 10683, dtype: datetime64[us]

In [22]:
#21
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Duration_Hour"] = df["Duration"].str.extract(r'(\d+)\s*h')[0]
df["Duration_Hour"] = pd.to_numeric(df["Duration_Hour"],errors = "coerce").fillna(0).astype(int)
display(df[["Duration","Duration_Hour"]])

      Duration  Duration_Hour
0       2h 50m              2
1       7h 25m              7
2          19h             19
3       5h 25m              5
4       4h 45m              4
...        ...            ...
10678   2h 30m              2
10679   2h 35m              2
10680       3h              3
10681   2h 40m              2
10682   8h 20m              8

[10683 rows x 2 columns]

In [26]:
#22
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Duration_Minute"] = df["Duration"].str.extract(r'(\d+)\s*m')[0]
df["Duration_Minute"] = pd.to_numeric(df["Duration_Minute"],errors = "coerce").fillna(0).astype(int)
display(df[["Duration","Duration_Minute"]])

      Duration  Duration_Minute
0       2h 50m               50
1       7h 25m               25
2          19h                0
3       5h 25m               25
4       4h 45m               45
...        ...              ...
10678   2h 30m               30
10679   2h 35m               35
10680       3h                0
10681   2h 40m               40
10682   8h 20m               20

[10683 rows x 2 columns]

In [28]:
#23
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Duration"] = pd.to_datetime(df["Duration"],errors = "coerce")
print("Hour From duration:")
df["Duration_Hour"] = df["Duration"].dt.hour
display(df[["Duration","Duration_Hour"]])
print("\nMinute from Duration:")
df["Duration_Minute"] = df["Duration"].dt.minute
display(df[["Duration","Duration_Minute"]])
print("\nOriginal Duration:")
display(df[["Duration"]])

Hour From duration:

C:\Users\hp\AppData\Local\Temp\ipykernel_22572\1131867545.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Duration"] = pd.to_datetime(df["Duration"],errors = "coerce")

              Duration  Duration_Hour
0     1-01-01 02:50:00            2.0
1     1-01-01 07:25:00            7.0
2     1-01-01 19:00:00           19.0
3     1-01-01 05:25:00            5.0
4     1-01-01 04:45:00            4.0
...                ...            ...
10678 1-01-01 02:30:00            2.0
10679 1-01-01 02:35:00            2.0
10680 1-01-01 03:00:00            3.0
10681 1-01-01 02:40:00            2.0
10682 1-01-01 08:20:00            8.0

[10683 rows x 2 columns]

Minute from Duration:

              Duration  Duration_Minute
0     1-01-01 02:50:00             50.0
1     1-01-01 07:25:00             25.0
2     1-01-01 19:00:00              0.0
3     1-01-01 05:25:00             25.0
4     1-01-01 04:45:00             45.0
...                ...              ...
10678 1-01-01 02:30:00             30.0
10679 1-01-01 02:35:00             35.0
10680 1-01-01 03:00:00              0.0
10681 1-01-01 02:40:00             40.0
10682 1-01-01 08:20:00             20.0

[10683 rows x 2 columns]

Original Duration:

              Duration
0     1-01-01 02:50:00
1     1-01-01 07:25:00
2     1-01-01 19:00:00
3     1-01-01 05:25:00
4     1-01-01 04:45:00
...                ...
10678 1-01-01 02:30:00
10679 1-01-01 02:35:00
10680 1-01-01 03:00:00
10681 1-01-01 02:40:00
10682 1-01-01 08:20:00

[10683 rows x 1 columns]

In [34]:
#24
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Total_Stops"] = df["Total_Stops"].replace({0:"non-stop"})
display(df.head(6))

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873

In [35]:
#25
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
df["Total_Stops"] = df["Total_Stops"].replace("non-stop",0)
df["Total_Stops"] = pd.to_numeric(df["Total_Stops"].str.extract(r"(\d+)")[0],errors = "coerce").fillna(0).astype(int)
display(df[["Total_Stops"]].head(10))

   Total_Stops
0            0
1            2
2            2
3            1
4            1
5            0
6            1
7            1
8            1
9            1

In [5]:
#26
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
route_columns = df["Route"].str.split("→",expand=True)
route_columns.columns = [
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]
df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]] = route_columns
display(df[["Route_1","Route_2","Route_3","Route_4","Route_5","Route_6"]].head(10))

  Route_1 Route_2 Route_3 Route_4 Route_5 Route_6
0    BLR      DEL     NaN     NaN     NaN     NaN
1    CCU     IXR     BBI      BLR     NaN     NaN
2    DEL     LKO     BOM      COK     NaN     NaN
3    CCU     NAG      BLR     NaN     NaN     NaN
4    BLR     NAG      DEL     NaN     NaN     NaN
5    CCU      BLR     NaN     NaN     NaN     NaN
6    BLR     BOM      DEL     NaN     NaN     NaN
7    BLR     BOM      DEL     NaN     NaN     NaN
8    BLR     BOM      DEL     NaN     NaN     NaN
9    DEL     BOM      COK     NaN     NaN     NaN

In [ ]:
#27
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
route_columns = df["Route"].str.split("→",expand=True)
route_columns.columns=[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]
df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]] = route_columns
print("Missing Values in Route_3:")
print(df["Route_3"].isnull().sum())
print("\nMissing Values in Route_4:")
display(df["Route_4"].isnull().sum())
print("\nMissing Values in Route_5:")
display(df["Route_5"].isnull().sum())

Missing Values in Route_3:
3492

Missing Values in Route_4:

np.int64(9117)

Missing Values in Route_5:

np.int64(10637)

In [14]:
#28
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
route_columns = df["Route"].str.split("→",expand=True)
route_columns.columns = [
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]
df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]] = route_columns
df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]] = df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]].fillna("None")
display(df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]].head(10))

  Route_1 Route_2 Route_3 Route_4 Route_5 Route_6
0    BLR      DEL    None    None    None    None
1    CCU     IXR     BBI      BLR    None    None
2    DEL     LKO     BOM      COK    None    None
3    CCU     NAG      BLR    None    None    None
4    BLR     NAG      DEL    None    None    None
5    CCU      BLR    None    None    None    None
6    BLR     BOM      DEL    None    None    None
7    BLR     BOM      DEL    None    None    None
8    BLR     BOM      DEL    None    None    None
9    DEL     BOM      COK    None    None    None

In [17]:
#29
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
route_columns = df["Route"].str.split("→",expand=True)
route_columns = [
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]
df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]] = route_columns
df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]] = df[[
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5",
    "Route_6"
]].fillna("None")
display(df["Route"])

0                    BLR → DEL
1        CCU → IXR → BBI → BLR
2        DEL → LKO → BOM → COK
3              CCU → NAG → BLR
4              BLR → NAG → DEL
                 ...
10678                CCU → BLR
10679                CCU → BLR
10680                BLR → DEL
10681                BLR → DEL
10682    DEL → GOI → BOM → COK
Name: Route, Length: 10683, dtype: str

In [18]:
#30
import pandas as pd
df = pd.read_csv('Data_Train.xlsx - Sheet1.csv')
X = df.drop(columns=["Price"])
y = df["Price"]
print("X shape:",X.shape)
print("y shape:",y.shape)
display(X.head())
display(y.head())

X shape: (10683, 10)
y shape: (10683,)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info

0     3897
1     7662
2    13882
3     6218
4    13302
Name: Price, dtype: int64