In [1]:
#1
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [2]:
#2
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df.tail(15)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
2025,100088,51,214004,173779.91,686,6,Pune,Premium,Branch,2022-04-22 00:00:00,Yes,Medium,39764.87,85,4.9
2026,101483,not_available,117573,261905.82,657,2,Pune,NaN,Branch,2022-07-02 00:00:00,Yes,Medium,39559.16,7,1.9
2027,100331,54,123511,280896.35,388,5,Pune,Premium,Mobile,2024-09-11 00:00:00,No,High,NaN,48,6.7
2028,101239,31,125500,189174.28,846,11,Delhi,Corporate,Agent,2022-04-08 00:00:00,Yes,Low,22161.09,102,8.5
2029,100467,NaN,101619,279182.04,392,3,Bangalore,Retail,Mobile,2023-07-26 00:00:00,Yes,High,37316.48,100,7.3
2030,100122,41,201611,40736.71,507,15,Bangalore,SME,Agent,2024-11-03 00:00:00,Yes,High,18815.18,58,7.2
2031,101639,61,128850,266135.8,840,9,Kolkata,SME,Mobile,2026-01-15 00:00:00,Yes,Low,34300.44,83,5.0
2032,101045,33,88037,129948.93,449,8,Mumbai,Premium,Mobile,2022-11-30 00:00:00,Yes,High,not_available,147,9.7
2033,101725,43,122756,36633.45,487,8,Pune,NaN,Mobile,2021-07-04 00:00:00,No,High,10165.71,14,6.4
2034,101096,18,189232,235131.72,306,10,hyderabad,SME,Mobile,2025-09-10 00:00:00,No,High,27227.44,85,5.9
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [3]:
#3
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df.sample(n=10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
42,100271,21,64499,abc,845,12,chennai,Premium,Agent,2022-03-10 00:00:00,Yes,Low,42189.4,98,6.4
801,100436,20,160720,142020.26,634,8,Kolkata,Corporate,Online,2024-10-14 00:00:00,Yes,Medium,32161.03,92,3.1
1525,100877,54,NaN,122633.18,689,10,Chennai,SME,Branch,2024-01-17 00:00:00,Yes,Medium,28460.03,56,7.0
321,101343,32,139914,284550.88,567,14,Chennai,Retail,Agent,2025-09-09 00:00:00,Yes,Medium,44019.65,116,5.6
1009,100139,29,177267,26460.51,743,12,Pune,Corporate,Branch,2025-11-30 00:00:00,No,Low,13410.02,148,2.4
667,101899,70,151888,298405.25,686,14,Chennai,Corporate,Mobile,2025-10-25 00:00:00,Yes,Medium,8253.39,93,4.7
473,100890,46,60585,132991.95,651,10,Delhi,SME,Mobile,2025-10-21 00:00:00,No,Medium,47675.81,74,5.0
196,100603,51,61321,13620.98,733,6,Pune,SME,Branch,2026-03-09 00:00:00,yes,High,26611.97,24,7.7
357,100186,46,209403,204226.77,425,2,Delhi,SME,Mobile,2023-12-20 00:00:00,Yes,High,24426.04,105,3.7
1920,101077,66,129131,196412.72,383,1,Delhi,Premium,Online,2022-07-04 00:00:00,Yes,High,15151.63,11,9.2

In [4]:
#4
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   str
 2   Annual_Income       1933 non-null   str
 3   Account_Balance     1912 non-null   str
 4   Credit_Score        2036 non-null   str
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   str
 7   Segment             1935 non-null   str
 8   Channel             2040 non-null   str
 9   Join_Date           1938 non-null   str
 10  Active              1981 non-null   str
 11  Risk_Level          2040 non-null   str
 12  Monthly_Spend       1931 non-null   str
 13  Transactions        2038 non-null   str
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), str(12)
memory usage: 239.2 KB

In [8]:
#5
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
print("Number of missing columns: ",df.isnull().sum())
print("The result isnull():",df.isnull())
print("The result isna():",df.isna())

Number of missing columns:  Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
The result isnull():       Customer_ID    Age  Annual_Income  Account_Balance  Credit_Score  \
0           False  False          False            False         False
1           False  False          False            False         False
2           False  False          False            False         False
3           False  False          False            False         False
4           False  False          False            False         False
...           ...    ...            ...              ...           ...
2035        False  False          False            False         False
2036        False  False          False            False         False
2037        False  False          False            False         False
2038        False  False          False            False         False
2039        False  False          False            False         False

      Tenure_Years   City  Segment  Channel  Join_Date  Active  Risk_Level  \
0            False  False    False    False      False   False       False
1            False  False    False    False      False   False       False
2            False  False    False    False      False   False       False
3            False  False    False    False      False   False       False
4            False  False    False    False      False   False       False
...            ...    ...      ...      ...        ...     ...         ...
2035         False  False    False    False      False   False       False
2036         False  False    False    False      False   False       False
2037         False  False    False    False      False   False       False
2038         False  False    False    False      False   False       False
2039         False  False    False    False       True   False       False

      Monthly_Spend  Transactions  Satisfaction_Score
0             False         False               False
1              True         False               False
2             False         False               False
3             False         False               False
4             False         False               False
...             ...           ...                 ...
2035          False         False               False
2036          False         False               False
2037          False         False               False
2038          False         False               False
2039          False         False               False

[2040 rows x 15 columns]
The result isna():       Customer_ID    Age  Annual_Income  Account_Balance  Credit_Score  \
0           False  False          False            False         False
1           False  False          False            False         False
2           False  False          False            False         False
3           False  False          False            False         False
4           False  False          False            False         False
...           ...    ...            ...              ...           ...
2035        False  False          False            False         False
2036        False  False          False            False         False
2037        False  False          False            False         False
2038        False  False          False            False         False
2039        False  False          False            False         False

      Tenure_Years   City  Segment  Channel  Join_Date  Active  Risk_Level  \
0            False  False    False    False      False   False       False
1            False  False    False    False      False   False       False
2            False  False    False    False      False   False       False
3            False  False    False    False      False   False       False
4            False  False    False    False      False   False       False
...            ...    ...      ...      ...        ...     ...         ...
2035         False  False    False    False      False   False       False
2036         False  False    False    False      False   False       False
2037         False  False    False    False      False   False       False
2038         False  False    False    False      False   False       False
2039         False  False    False    False       True   False       False

      Monthly_Spend  Transactions  Satisfaction_Score
0             False         False               False
1              True         False               False
2             False         False               False
3             False         False               False
4             False         False               False
...             ...           ...                 ...
2035          False         False               False
2036          False         False               False
2037          False         False               False
2038          False         False               False
2039          False         False               False

[2040 rows x 15 columns]

In [1]:
#6
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df.duplicated().sum()

np.int64(40)

In [2]:
#7
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df_new = df.drop_duplicates()
display(df_new)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [3]:
#8
import pandas as pd
df = pd.read_csv("customer_analytics - customer_analytics.csv")
numeric_df = df.select_dtypes(include=['number'])
print("Currently numeric columns:")
print(numeric_df.columns.tolist())
print("\nPotentially Numeric Object Columns:")
for column in df.select_dtypes(include=['object']).columns:
    converted = pd.to_numeric(df[column],errors = 'coerce')
    numeric_values = converted.notna().sum()
    original_values = df[column].notna().sum()
    if numeric_values > 0 and numeric_values < original_values:
        print(column)

Currently numeric columns:
['Customer_ID', 'Tenure_Years', 'Satisfaction_Score']

Potentially Numeric Object Columns:
Age
Annual_Income
Account_Balance
Credit_Score
Active
Monthly_Spend
Transactions

C:\Users\hp\AppData\Local\Temp\ipykernel_11200\902344177.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include=['object']).columns:

In [5]:
#9
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df['Age'] = pd.to_numeric(df["Age"],errors = 'coerce')
median_age = df['Age'].median()
print("Median age:",median_age)
df['Age'] = df["Age"].fillna(median_age)
print("\nAge after cleaning: ")
print(df["Age"].head(20))
print("/nData Type:")
print(df["Age"].dtype)
print("\nMissing Age values:")
print(df["Age"].isnull().sum())

Median age: 47.0

Age after cleaning:
0     55.0
1     32.0
2     23.0
3     66.0
4     67.0
5     68.0
6     47.0
7     65.0
8     63.0
9     42.0
10    47.0
11    25.0
12    66.0
13    22.0
14    52.0
15    45.0
16    27.0
17    53.0
18    53.0
19    64.0
Name: Age, dtype: float64
/nData Type:
float64

Missing Age values:
0

In [12]:
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors = "coerce")
median_Annual_Income = df["Annual_Income"].median()
print("Median Annual Income:",median_Annual_Income)
df["Annual_Income"] = df["Annual_Income"].fillna(median_Annual_Income)
df["Annual_Income"] = df["Annual_Income"].astype(float)
print("\nAnnual Income after cleaning:")
print(df["Annual_Income"].head(10))
print("\nData type:")
print(df["Annual_Income"].dtype)
print("\nMissing values:")
print(df["Annual_Income"].isnull().sum())

Median Annual Income: 139999.5

Annual Income after cleaning:
0     44033.0
1    215546.0
2    226403.0
3     87824.0
4     31570.0
5     37087.0
6     67229.0
7    139999.5
8    153267.0
9    139999.5
Name: Annual_Income, dtype: float64

Data type:
float64

Missing values:
0

In [20]:
#11
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors = "coerce")
mean_acc_bal = df["Account_Balance"].mean()
print("Mean of the account balance:",mean_acc_bal)
df["Account_Balance"] = df["Account_Balance"].fillna(mean_acc_bal)
print("\nAccount Balance after cleaning:")
print(df["Account_Balance"].head(10))
print("\nMissing Values:")
print(df["Account_Balance"].isnull().sum())

Mean of the account balance: 151049.05422603106

Account Balance after cleaning:
0    111350.85
1    254378.37
2    159975.42
3    295741.60
4    242423.78
5    180084.44
6     99629.81
7     61030.94
8    221707.97
9     41126.84
Name: Account_Balance, dtype: float64

Missing Values:
0

In [25]:
#12
import pandas as pd
df = pd.read_csv("customer_analytics - customer_analytics.csv")
df["Credit_Score"] = pd.to_numeric(df["Credit_Score"],errors = "coerce")
median_credit_score = df["Credit_Score"].median()
print("Median Credit score:",median_credit_score)
df["Credit_Score"] = df["Credit_Score"].fillna(median_credit_score)
df["Credit_Score"] = df["Credit_Score"].astype(int)
print("\nCredit score after cleaning:")
print(df["Credit_Score"].head(20))
print("\nNo of missing values:")
print(df["Credit_Score"].isnull().sum())
print("\nData type:")
print(df["Credit_Score"].dtype)

Median Credit score: 570.0

Credit score after cleaning:
0     772
1     374
2     668
3     315
4     370
5     738
6     464
7     554
8     508
9     556
10    341
11    477
12    643
13    542
14    443
15    693
16    746
17    314
18    315
19    701
Name: Credit_Score, dtype: int64

No of missing values:
0

Data type:
int64

In [2]:
#13
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors = "coerce")
median_Monthly_Spend = df["Monthly_Spend"].median()
print("Median of monthly spend:",median_Monthly_Spend)
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(median_Monthly_Spend)
df["Monthly_Spend"] = df["Monthly_Spend"].astype(float)
print("Data After Cleaning:")
print(df.head(20))

Median of monthly spend: 24646.77
Data After Cleaning:
    Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0        101317  55         44033       111350.85          772             3
1        101001  32        215546       254378.37          374             8
2        101069  23        226403       159975.42          668            12
3        101968  66         87824        295741.6          315            14
4        100530  67         31570       242423.78          370             4
5        101334  68         37087       180084.44          738             1
6        100415  47         67229        99629.81          464             4
7        100983  65           NaN        61030.94          554            15
8        100417  63        153267       221707.97          508             5
9        101472  42       missing        41126.84          556             3
10       101525  47        178741        22931.96          341             1
11       101576  25         93673        65086.87          477            13
12       100252  66        108309       216944.85          643            10
13       101622  22        106816        70169.08          542             4
14       100071  52       missing       119810.62          443            13
15       101107  45         53671       290179.08          693             4
16       101363  27        192132       193980.13          746            12
17       100351  53        108186        31442.42          314             0
18       101392  53        193933       250519.78          315             9
19       101088  64        175949        65169.27          701             1

         City    Segment Channel            Join_Date Active Risk_Level  \
0   Bangalore        SME   Agent  2022-08-15 00:00:00    Yes        Low
1       Delhi     Retail   Agent  2025-01-11 00:00:00    Yes       High
2     Chennai    Premium   Agent  2024-08-01 00:00:00     No     Medium
3      Mumbai    Premium   Agent  2021-05-15 00:00:00    Yes       High
4   bangalore     Retail   Agent  2026-02-03 00:00:00     No       High
5     Chennai    Premium   Agent  2023-06-04 00:00:00    Yes        Low
6     Chennai     Retail  Online  2024-01-16 00:00:00    Yes       High
7     Kolkata        SME   Agent  2024-06-26 00:00:00    Yes     Medium
8   Hyderabad    Premium  Mobile  2025-03-12 00:00:00    Yes       High
9     Kolkata  Corporate  Mobile  2021-10-07 00:00:00    Yes     Medium
10  Hyderabad     Retail  Mobile  2023-03-02 00:00:00    Yes       High
11  Bangalore    Premium  Online  2025-11-22 00:00:00    Yes       High
12    Chennai  Corporate  Mobile  2021-06-25 00:00:00     No     Medium
13    Kolkata    Premium  Mobile  2025-11-19 00:00:00    Yes       High
14        NaN    Premium  Branch  2025-08-26 00:00:00    Yes       High
15       Pune        SME   Agent  2024-05-05 00:00:00     No     Medium
16    Kolkata        SME   Agent  2022-01-07 00:00:00     No        Low
17  Hyderabad  Corporate  Mobile  2022-05-25 00:00:00    NaN       High
18        NaN     Retail   Agent  2022-10-07 00:00:00    Yes       High
19  Hyderabad    Premium   Agent  2023-08-10 00:00:00     No        Low

    Monthly_Spend Transactions  Satisfaction_Score
0        23066.19          135                 3.1
1        24646.77          106                 8.2
2        28536.34          146                 6.3
3        12869.71          115                 9.7
4        34163.02           94                 3.7
5        15121.16            6                 8.5
6        17655.61           31                 2.8
7         1720.85          139                 9.7
8        38043.07           76                 7.1
9        11472.36          124                 9.1
10       24646.77           78                 5.6
11       24777.75           56                 8.1
12        9746.99           15                 3.9
13       32337.34           66                 3.1
14       48482.81           18                 9.1
15       49870.37           31                 4.4
16        7111.13          110                 9.1
17       24056.68          121                 9.2
18       32432.32           95                 9.3
19       19941.13          118                 7.5

In [6]:
#14
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Transactions"] = pd.to_numeric(df["Transactions"],errors = "coerce")
median_transactions = df["Transactions"].median()
print("Median of transactions:",median_transactions)
df["Transactions"] = df["Transactions"].fillna(median_transactions)
df["Transactions"] = df["Transactions"].astype(int)
print("\nData After Cleaning:")
print(df.head(20))
print("\nData type:")
print(df["Transactions"].dtype)
print("\nMissing Values:")
print(df["Transactions"].isna().sum())

Median of transactions: 76.0

Data After Cleaning:
    Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0        101317  55         44033       111350.85          772             3
1        101001  32        215546       254378.37          374             8
2        101069  23        226403       159975.42          668            12
3        101968  66         87824        295741.6          315            14
4        100530  67         31570       242423.78          370             4
5        101334  68         37087       180084.44          738             1
6        100415  47         67229        99629.81          464             4
7        100983  65           NaN        61030.94          554            15
8        100417  63        153267       221707.97          508             5
9        101472  42       missing        41126.84          556             3
10       101525  47        178741        22931.96          341             1
11       101576  25         93673        65086.87          477            13
12       100252  66        108309       216944.85          643            10
13       101622  22        106816        70169.08          542             4
14       100071  52       missing       119810.62          443            13
15       101107  45         53671       290179.08          693             4
16       101363  27        192132       193980.13          746            12
17       100351  53        108186        31442.42          314             0
18       101392  53        193933       250519.78          315             9
19       101088  64        175949        65169.27          701             1

         City    Segment Channel            Join_Date Active Risk_Level  \
0   Bangalore        SME   Agent  2022-08-15 00:00:00    Yes        Low
1       Delhi     Retail   Agent  2025-01-11 00:00:00    Yes       High
2     Chennai    Premium   Agent  2024-08-01 00:00:00     No     Medium
3      Mumbai    Premium   Agent  2021-05-15 00:00:00    Yes       High
4   bangalore     Retail   Agent  2026-02-03 00:00:00     No       High
5     Chennai    Premium   Agent  2023-06-04 00:00:00    Yes        Low
6     Chennai     Retail  Online  2024-01-16 00:00:00    Yes       High
7     Kolkata        SME   Agent  2024-06-26 00:00:00    Yes     Medium
8   Hyderabad    Premium  Mobile  2025-03-12 00:00:00    Yes       High
9     Kolkata  Corporate  Mobile  2021-10-07 00:00:00    Yes     Medium
10  Hyderabad     Retail  Mobile  2023-03-02 00:00:00    Yes       High
11  Bangalore    Premium  Online  2025-11-22 00:00:00    Yes       High
12    Chennai  Corporate  Mobile  2021-06-25 00:00:00     No     Medium
13    Kolkata    Premium  Mobile  2025-11-19 00:00:00    Yes       High
14        NaN    Premium  Branch  2025-08-26 00:00:00    Yes       High
15       Pune        SME   Agent  2024-05-05 00:00:00     No     Medium
16    Kolkata        SME   Agent  2022-01-07 00:00:00     No        Low
17  Hyderabad  Corporate  Mobile  2022-05-25 00:00:00    NaN       High
18        NaN     Retail   Agent  2022-10-07 00:00:00    Yes       High
19  Hyderabad    Premium   Agent  2023-08-10 00:00:00     No        Low

   Monthly_Spend  Transactions  Satisfaction_Score
0       23066.19           135                 3.1
1            NaN           106                 8.2
2       28536.34           146                 6.3
3       12869.71           115                 9.7
4       34163.02            94                 3.7
5       15121.16             6                 8.5
6       17655.61            31                 2.8
7        1720.85           139                 9.7
8       38043.07            76                 7.1
9       11472.36           124                 9.1
10           NaN            78                 5.6
11      24777.75            56                 8.1
12       9746.99            15                 3.9
13      32337.34            66                 3.1
14      48482.81            18                 9.1
15      49870.37            31                 4.4
16       7111.13           110                 9.1
17      24056.68           121                 9.2
18      32432.32            95                 9.3
19      19941.13           118                 7.5

Data type:
int64

Missing Values:
0

In [8]:
#15
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"],errors = "coerce")
mean_satisfaction_score = df["Satisfaction_Score"].mean()
print("mean of satisfaction score:",mean_satisfaction_score)
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(mean_satisfaction_score)
df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)
print("\nData After cleaning:")
print(df.head(20))
print("\nData Type:")
print(df["Satisfaction_Score"].dtype)
print("\nMissing Values:")
print(df["Satisfaction_Score"].isna().sum())

mean of satisfaction score: 5.595907928388747

Data After cleaning:
    Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0        101317  55         44033       111350.85          772             3
1        101001  32        215546       254378.37          374             8
2        101069  23        226403       159975.42          668            12
3        101968  66         87824        295741.6          315            14
4        100530  67         31570       242423.78          370             4
5        101334  68         37087       180084.44          738             1
6        100415  47         67229        99629.81          464             4
7        100983  65           NaN        61030.94          554            15
8        100417  63        153267       221707.97          508             5
9        101472  42       missing        41126.84          556             3
10       101525  47        178741        22931.96          341             1
11       101576  25         93673        65086.87          477            13
12       100252  66        108309       216944.85          643            10
13       101622  22        106816        70169.08          542             4
14       100071  52       missing       119810.62          443            13
15       101107  45         53671       290179.08          693             4
16       101363  27        192132       193980.13          746            12
17       100351  53        108186        31442.42          314             0
18       101392  53        193933       250519.78          315             9
19       101088  64        175949        65169.27          701             1

         City    Segment Channel            Join_Date Active Risk_Level  \
0   Bangalore        SME   Agent  2022-08-15 00:00:00    Yes        Low
1       Delhi     Retail   Agent  2025-01-11 00:00:00    Yes       High
2     Chennai    Premium   Agent  2024-08-01 00:00:00     No     Medium
3      Mumbai    Premium   Agent  2021-05-15 00:00:00    Yes       High
4   bangalore     Retail   Agent  2026-02-03 00:00:00     No       High
5     Chennai    Premium   Agent  2023-06-04 00:00:00    Yes        Low
6     Chennai     Retail  Online  2024-01-16 00:00:00    Yes       High
7     Kolkata        SME   Agent  2024-06-26 00:00:00    Yes     Medium
8   Hyderabad    Premium  Mobile  2025-03-12 00:00:00    Yes       High
9     Kolkata  Corporate  Mobile  2021-10-07 00:00:00    Yes     Medium
10  Hyderabad     Retail  Mobile  2023-03-02 00:00:00    Yes       High
11  Bangalore    Premium  Online  2025-11-22 00:00:00    Yes       High
12    Chennai  Corporate  Mobile  2021-06-25 00:00:00     No     Medium
13    Kolkata    Premium  Mobile  2025-11-19 00:00:00    Yes       High
14        NaN    Premium  Branch  2025-08-26 00:00:00    Yes       High
15       Pune        SME   Agent  2024-05-05 00:00:00     No     Medium
16    Kolkata        SME   Agent  2022-01-07 00:00:00     No        Low
17  Hyderabad  Corporate  Mobile  2022-05-25 00:00:00    NaN       High
18        NaN     Retail   Agent  2022-10-07 00:00:00    Yes       High
19  Hyderabad    Premium   Agent  2023-08-10 00:00:00     No        Low

   Monthly_Spend Transactions  Satisfaction_Score
0       23066.19          135                 3.1
1            NaN          106                 8.2
2       28536.34          146                 6.3
3       12869.71          115                 9.7
4       34163.02           94                 3.7
5       15121.16            6                 8.5
6       17655.61           31                 2.8
7        1720.85          139                 9.7
8       38043.07           76                 7.1
9       11472.36          124                 9.1
10           NaN           78                 5.6
11      24777.75           56                 8.1
12       9746.99           15                 3.9
13      32337.34           66                 3.1
14      48482.81           18                 9.1
15      49870.37           31                 4.4
16       7111.13          110                 9.1
17      24056.68          121                 9.2
18      32432.32           95                 9.3
19      19941.13          118                 7.5

Data Type:
float64

Missing Values:
0

In [12]:
#16
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
print("Join_Date")
print(df["Join_Date"].head(20))
print("\nData Type:")
print(df["Join_Date"].dtype)
print("\nMissing Values:")
print(df["Join_Date"].isnull().sum())
print("\nUnique Join_Date Values:")
print(df["Join_Date"].dropna().unique()[:20])

Join_Date
0     2022-08-15 00:00:00
1     2025-01-11 00:00:00
2     2024-08-01 00:00:00
3     2021-05-15 00:00:00
4     2026-02-03 00:00:00
5     2023-06-04 00:00:00
6     2024-01-16 00:00:00
7     2024-06-26 00:00:00
8     2025-03-12 00:00:00
9     2021-10-07 00:00:00
10    2023-03-02 00:00:00
11    2025-11-22 00:00:00
12    2021-06-25 00:00:00
13    2025-11-19 00:00:00
14    2025-08-26 00:00:00
15    2024-05-05 00:00:00
16    2022-01-07 00:00:00
17    2022-05-25 00:00:00
18    2022-10-07 00:00:00
19    2023-08-10 00:00:00
Name: Join_Date, dtype: str

Data Type:
str

Missing Values:
102

Unique Join_Date Values:
<StringArray>
['2022-08-15 00:00:00', '2025-01-11 00:00:00', '2024-08-01 00:00:00',
 '2021-05-15 00:00:00', '2026-02-03 00:00:00', '2023-06-04 00:00:00',
 '2024-01-16 00:00:00', '2024-06-26 00:00:00', '2025-03-12 00:00:00',
 '2021-10-07 00:00:00', '2023-03-02 00:00:00', '2025-11-22 00:00:00',
 '2021-06-25 00:00:00', '2025-11-19 00:00:00', '2025-08-26 00:00:00',
 '2024-05-05 00:00:00', '2022-01-07 00:00:00', '2022-05-25 00:00:00',
 '2022-10-07 00:00:00', '2023-08-10 00:00:00']
Length: 20, dtype: str

In [ ]:
#17 and #18
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = "coerce")
df["Join_Date"] = df["Join_Date"].astype('datetime64[ns]')
print("Date After cleaning:")
print(df.head(20))

Date After cleaning:
    Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0        101317  55         44033       111350.85          772             3
1        101001  32        215546       254378.37          374             8
2        101069  23        226403       159975.42          668            12
3        101968  66         87824        295741.6          315            14
4        100530  67         31570       242423.78          370             4
5        101334  68         37087       180084.44          738             1
6        100415  47         67229        99629.81          464             4
7        100983  65           NaN        61030.94          554            15
8        100417  63        153267       221707.97          508             5
9        101472  42       missing        41126.84          556             3
10       101525  47        178741        22931.96          341             1
11       101576  25         93673        65086.87          477            13
12       100252  66        108309       216944.85          643            10
13       101622  22        106816        70169.08          542             4
14       100071  52       missing       119810.62          443            13
15       101107  45         53671       290179.08          693             4
16       101363  27        192132       193980.13          746            12
17       100351  53        108186        31442.42          314             0
18       101392  53        193933       250519.78          315             9
19       101088  64        175949        65169.27          701             1

         City    Segment Channel  Join_Date Active Risk_Level Monthly_Spend  \
0   Bangalore        SME   Agent 2022-08-15    Yes        Low      23066.19
1       Delhi     Retail   Agent 2025-01-11    Yes       High           NaN
2     Chennai    Premium   Agent 2024-08-01     No     Medium      28536.34
3      Mumbai    Premium   Agent 2021-05-15    Yes       High      12869.71
4   bangalore     Retail   Agent 2026-02-03     No       High      34163.02
5     Chennai    Premium   Agent 2023-06-04    Yes        Low      15121.16
6     Chennai     Retail  Online 2024-01-16    Yes       High      17655.61
7     Kolkata        SME   Agent 2024-06-26    Yes     Medium       1720.85
8   Hyderabad    Premium  Mobile 2025-03-12    Yes       High      38043.07
9     Kolkata  Corporate  Mobile 2021-10-07    Yes     Medium      11472.36
10  Hyderabad     Retail  Mobile 2023-03-02    Yes       High           NaN
11  Bangalore    Premium  Online 2025-11-22    Yes       High      24777.75
12    Chennai  Corporate  Mobile 2021-06-25     No     Medium       9746.99
13    Kolkata    Premium  Mobile 2025-11-19    Yes       High      32337.34
14        NaN    Premium  Branch 2025-08-26    Yes       High      48482.81
15       Pune        SME   Agent 2024-05-05     No     Medium      49870.37
16    Kolkata        SME   Agent 2022-01-07     No        Low       7111.13
17  Hyderabad  Corporate  Mobile 2022-05-25    NaN       High      24056.68
18        NaN     Retail   Agent 2022-10-07    Yes       High      32432.32
19  Hyderabad    Premium   Agent 2023-08-10     No        Low      19941.13

   Transactions  Satisfaction_Score
0           135                 3.1
1           106                 8.2
2           146                 6.3
3           115                 9.7
4            94                 3.7
5             6                 8.5
6            31                 2.8
7           139                 9.7
8            76                 7.1
9           124                 9.1
10           78                 5.6
11           56                 8.1
12           15                 3.9
13           66                 3.1
14           18                 9.1
15           31                 4.4
16          110                 9.1
17          121                 9.2
18           95                 9.3
19          118                 7.5

In [ ]:
#17
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors = "coerce")
print("Date after cleaning:")
print(df.head(20))
print("\nData Type:")
print(df["Join_Date"].dtype)
print("\nMissing/Invalid Dates:")
print(df["Join_Date"].isnull().sum())

Date after cleaning:
    Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0        101317  55         44033       111350.85          772             3
1        101001  32        215546       254378.37          374             8
2        101069  23        226403       159975.42          668            12
3        101968  66         87824        295741.6          315            14
4        100530  67         31570       242423.78          370             4
5        101334  68         37087       180084.44          738             1
6        100415  47         67229        99629.81          464             4
7        100983  65           NaN        61030.94          554            15
8        100417  63        153267       221707.97          508             5
9        101472  42       missing        41126.84          556             3
10       101525  47        178741        22931.96          341             1
11       101576  25         93673        65086.87          477            13
12       100252  66        108309       216944.85          643            10
13       101622  22        106816        70169.08          542             4
14       100071  52       missing       119810.62          443            13
15       101107  45         53671       290179.08          693             4
16       101363  27        192132       193980.13          746            12
17       100351  53        108186        31442.42          314             0
18       101392  53        193933       250519.78          315             9
19       101088  64        175949        65169.27          701             1

         City    Segment Channel  Join_Date Active Risk_Level Monthly_Spend  \
0   Bangalore        SME   Agent 2022-08-15    Yes        Low      23066.19
1       Delhi     Retail   Agent 2025-01-11    Yes       High           NaN
2     Chennai    Premium   Agent 2024-08-01     No     Medium      28536.34
3      Mumbai    Premium   Agent 2021-05-15    Yes       High      12869.71
4   bangalore     Retail   Agent 2026-02-03     No       High      34163.02
5     Chennai    Premium   Agent 2023-06-04    Yes        Low      15121.16
6     Chennai     Retail  Online 2024-01-16    Yes       High      17655.61
7     Kolkata        SME   Agent 2024-06-26    Yes     Medium       1720.85
8   Hyderabad    Premium  Mobile 2025-03-12    Yes       High      38043.07
9     Kolkata  Corporate  Mobile 2021-10-07    Yes     Medium      11472.36
10  Hyderabad     Retail  Mobile 2023-03-02    Yes       High           NaN
11  Bangalore    Premium  Online 2025-11-22    Yes       High      24777.75
12    Chennai  Corporate  Mobile 2021-06-25     No     Medium       9746.99
13    Kolkata    Premium  Mobile 2025-11-19    Yes       High      32337.34
14        NaN    Premium  Branch 2025-08-26    Yes       High      48482.81
15       Pune        SME   Agent 2024-05-05     No     Medium      49870.37
16    Kolkata        SME   Agent 2022-01-07     No        Low       7111.13
17  Hyderabad  Corporate  Mobile 2022-05-25    NaN       High      24056.68
18        NaN     Retail   Agent 2022-10-07    Yes       High      32432.32
19  Hyderabad    Premium   Agent 2023-08-10     No        Low      19941.13

   Transactions  Satisfaction_Score
0           135                 3.1
1           106                 8.2
2           146                 6.3
3           115                 9.7
4            94                 3.7
5             6                 8.5
6            31                 2.8
7           139                 9.7
8            76                 7.1
9           124                 9.1
10           78                 5.6
11           56                 8.1
12           15                 3.9
13           66                 3.1
14           18                 9.1
15           31                 4.4
16          110                 9.1
17          121                 9.2
18           95                 9.3
19          118                 7.5

Data Type:
datetime64[us]

Missing/Invalid Dates:
128

In [2]:
#19
import pandas as pd
df = pd.read_csv("customer_analytics - customer_analytics.csv")
df["City"] = df["City"].replace({
    "mumbai":"Mumbai",
     "MUMBAI":"Mumbai"
})
print("Check Frequency distribution:")
print(df["City"].value_counts())

Check Frequency distribution:
City
Mumbai       314
Hyderabad    278
Delhi        273
Kolkata      262
Pune         256
Chennai      242
Bangalore    236
hyderabad     20
bangalore     18
pune          18
delhi         15
kolkata       14
chennai       13
Name: count, dtype: int64

In [6]:
#20
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
print("Check Frequency:")
print(df["Segment"].value_counts())
print("\nMissing Values:")
print(df["Segment"].isnull().sum())
most_common_segment = df["Segment"].value_counts().idxmax()
print("\nMost common segment:",most_common_segment)
df["Segment"] = df["Segment"].fillna(most_common_segment)
print("\nMissing values after filling:")
print(df["Segment"].isnull().sum())
print("\nFinal segment frequency:")
print(df["Segment"].value_counts())

Check Frequency:
Segment
Premium      523
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

Missing Values:
105

Most common segment: Premium

Missing values after filling:
0

Final segment frequency:
Segment
Premium      628
Retail       481
Corporate    475
SME          456
Name: count, dtype: int64

In [11]:
#21
import pandas as pd
from IPython.display import display
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Active"] = df["Active"].replace({
    "Yes":"Yes","No":"No","Y":"Yes","N":"No","YES":"Yes","NO":"No","yes":"Yes","no":"No","1":"Yes","0":"No"
    })
print("Check Frequency:")
print(df["Active"].value_counts())
print("\nData After replacing:")
display(df.head(10))

Check Frequency:
Active
Yes    1371
No      610
Name: count, dtype: int64

Data After replacing:

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [15]:
#22
import pandas as pd
from IPython.display import display
df = pd.read_csv('customer_analytics - customer_analytics.csv')
print("Check the distribution:")
print(df["Risk_Level"].value_counts())
print("\nMissing Values:")
print(df["Risk_Level"].isnull().sum())
print("\nFinal Class Distribution:")
df["Risk_Level"].value_counts()

Check the distribution:
Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

Missing Values:
0

Final Class Distribution:

Risk_Level
High      1009
Low        548
Medium     483
Name: count, dtype: int64

In [21]:
#23
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df.rename(columns={"Customer_ID":"Customer_ID","Annual_Income":"AnnualIncome","Account_Balance":"AccountBalance","Credit_Score":"CreditScore","Tenure_Years":"Tenure","Join_Date":"CustomerJoinDate","Risk_Level":"RiskLevel","Monthly_Spend":"MonthlySpend","Satisfaction_Score":"SatisfactionScore"},inplace=True)
df.head(10)

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [31]:
#24
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df = df.add_prefix("Customer_")
df.head(10)

,Customer_Customer_ID,Customer_Age,Customer_Annual_Income,Customer_Account_Balance,Customer_Credit_Score,Customer_Tenure_Years,Customer_City,Customer_Segment,Customer_Channel,Customer_Join_Date,Customer_Active,Customer_Risk_Level,Customer_Monthly_Spend,Customer_Transactions,Customer_Satisfaction_Score
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
5,101334,68,37087,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5
6,100415,47,67229,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7
8,100417,63,153267,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1
9,101472,42,missing,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1

In [34]:
#26
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors = "coerce")
df["Income_Lakhs"] = df["Annual_Income"]/100000
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Income_Lakhs
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,0.44033
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,2.15546
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,2.26403
3,101968,66,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,0.87824
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,0.31570
5,101334,68,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5,0.37087
6,100415,47,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8,0.67229
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7,NaN
8,100417,63,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1,1.53267
9,101472,42,NaN,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1,NaN

In [38]:
#27
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors = "coerce")
df["MonthlyIncome"] = df["Annual_Income"]/12
df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors = "coerce")
df["Income_After_Spending"] = df["MonthlyIncome"]-df["Monthly_Spend"]
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,MonthlyIncome,Income_After_Spending
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,3669.416667,-19396.773333
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,17962.166667,NaN
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,18866.916667,-9669.423333
3,101968,66,87824.0,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,7318.666667,-5551.043333
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,2630.833333,-31532.186667
5,101334,68,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5,3090.583333,-12030.576667
6,100415,47,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8,5602.416667,-12053.193333
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7,NaN,NaN
8,100417,63,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1,12772.250000,-25270.820000
9,101472,42,NaN,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1,NaN,NaN

In [40]:
#28
import pandas as pd
df = pd.read_csv('customer_analytics - customer_analytics.csv')
df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors = "coerce")
df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors="coerce")
df["Balance_Income_Ratio"] = df["Account_Balance"]/df["Annual_Income"]
df.head(10)

,Customer_ID,Age,Annual_Income,Account_Balance,Credit_Score,Tenure_Years,City,Segment,Channel,Join_Date,Active,Risk_Level,Monthly_Spend,Transactions,Satisfaction_Score,Balance_Income_Ratio
0,101317,55,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1,2.528805
1,101001,32,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2,1.180158
2,101069,23,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3,0.706596
3,101968,66,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7,3.367435
4,100530,67,31570.0,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7,7.678929
5,101334,68,37087.0,180084.44,738,1,Chennai,Premium,Agent,2023-06-04 00:00:00,Yes,Low,15121.16,6,8.5,4.855730
6,100415,47,67229.0,99629.81,464,4,Chennai,Retail,Online,2024-01-16 00:00:00,Yes,High,17655.61,31,2.8,1.481947
7,100983,65,NaN,61030.94,554,15,Kolkata,SME,Agent,2024-06-26 00:00:00,Yes,Medium,1720.85,139,9.7,NaN
8,100417,63,153267.0,221707.97,508,5,Hyderabad,Premium,Mobile,2025-03-12 00:00:00,Yes,High,38043.07,76,7.1,1.446547
9,101472,42,NaN,41126.84,556,3,Kolkata,Corporate,Mobile,2021-10-07 00:00:00,Yes,Medium,11472.36,124,9.1,NaN