In [1]:
#1
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
display(df.head(10))

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

In [2]:
#2
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df.shape

(2000, 15)

In [8]:
#3
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
print("All column Names:")
print(df.columns.tolist())
print("\nColumns with leading/trailing spaces:")
for column in df.columns:
    if column != column.strip():
        print(repr(column))

print("\nColumn names with inconsistent capitalization:")
for column in df.columns:
    if column != column.lower() and column != column.upper():
        print(repr(column))

All column Names:
['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years', 'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender', 'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text']

Columns with leading/trailing spaces:

Column names with inconsistent capitalization:
'Customer ID'
'Age'
'credit Score'
'City'

In [12]:
#4
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
display(df.dtypes)

Customer ID             str
Age                     str
income_usd              str
credit Score            str
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                    str
customer_segment        str
gender                  str
is_active               str
churn_flag              str
signup_date             str
lead_source             str
notes_text              str
dtype: object

In [18]:
#5
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
print("Number of missing values:")
print(df.isnull().sum())
print("\nPercentage of missing values:")
print(df.isnull().mean()*100)

Number of missing values:
Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

Percentage of missing values:
Customer ID          1.00
Age                 16.55
income_usd          22.00
credit Score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
City                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

In [25]:
#6
import pandas as pd
df = pd.read_csv("customer_data - customer_data.csv")
missing_customer_id = df[df["Customer ID"].isnull()]
print(missing_customer_id)

     Customer ID          Age   income_usd credit Score  tenure_years  \
162          NaN           18  61780.99213  715.4452325     10.137001
226          NaN           18  58188.80528  737.9284458     15.655950
300          NaN          NaN  93665.74378  703.9692987     12.723292
421          NaN   29.6 years          NaN  641.3441152      8.940646
770          NaN  20.39545706  92366.06753  767.8048841      4.524943
821          NaN  46.41996378  81119.71831  597.3307848      1.076200
876          NaN  36.57634009  76629.87047   699.109735      4.977078
993          NaN  47.54933612          NaN          NaN      0.693710
1023         NaN          NaN  34219.41505          NaN      3.779121
1188         NaN  28.97406958          NaN      744 pts      7.947965
1202         NaN  42.23152645  35310.77625  684.8618643      2.465432
1212         NaN  56.44358785      $99,697  749.3298384      3.743193
1248         NaN  34.60645101  96811.19575  798.1150352      1.551247
1338         NaN   26.5 years      $89,682  692.0794813      1.877392
1346         NaN  46.22898842  60122.78196  684.8548451      3.837557
1448         NaN           18          NaN   628.337014      7.137356
1451         NaN  47.20187446  28270.08329  549.3662455      3.019237
1462         NaN  49.99203599  58348.28529  511.5806801      2.775352
1564         NaN  42.96550781      $64,045      561 pts      4.549291
1652         NaN  33.27510593  37475.10034          NaN      4.345689

      monthly_visits  satisfaction       City customer_segment  gender  \
162              5.0      3.179153      Delhi          UNKNOWN  Female
226             12.0      3.330254    Chennai         Consumer  Female
300              7.0           NaN       Pune              SMB  Female
421              5.0      3.687539        NaN         Consumer  Female
770              3.0      4.358065     Mumbai       Enterprise       f
821              5.0      4.346306      Delhi         consumer       f
876              6.0      2.700057     Mumbai         consumer       M
993              4.0      3.659781        NaN       Enterprise     NaN
1023             4.0      3.529211  Hyderabad              NaN       M
1188             8.0      2.379383  Hyderabad         Consumer       f
1202             6.0      4.979391      Delhi              SMB       m
1212             6.0           NaN        NaN              NaN       M
1248             5.0      3.288656     Mumbai             SMB.       M
1338             4.0      3.783551       Pune         Consumer       m
1346             2.0      4.267750     Mumbai         consumer       F
1448             5.0           NaN       Pune       Enterprise  Female
1451             6.0      3.441021  Hyderabad              SMB       m
1462             NaN           NaN     Mumbai              SMB  Female
1564             4.0      3.513904    Chennai         Consumer       m
1652            11.0   -999.000000     Mumbai              SMB       f

     is_active churn_flag signup_date lead_source        notes_text
162        NaN         No  2021-04-22     website  follow-up needed
226          Y        NaN  2022-03-18    Referral            normal
300          1         No         NaN       Email  follow-up needed
421          1         No  2021-12-05     Unknown               NaN
770          N         No  2021-09-05         ???               NaN
821          1        Yes  2022-12-26       Email               NaN
876          N        Yes  2021-07-01    referral              good
993        NaN         No  2024-07-09    Referral      late payment
1023         N         No  2023-07-05  Google Ads                ok
1188       Yes         No  2026-06-06         NaN            urgent
1202         1         No  2024-10-10  google_ads      late payment
1212         Y        Yes  2024-07-18         WEB               NaN
1248         N         No  2023-09-16      Social  follow-up needed
1338         N         No  2023-12-04         WEB               NaN
1346         N        Yes  2023-01-01    referral  follow-up needed
1448        no        NaN  2024-08-25  Google Ads               NaN
1451       yes        Yes  2023-10-12     Unknown              good
1462        no         No  2024-07-07         NaN               NaN
1564        No         No  03/08/2023       Email               NaN
1652       NaN        NaN  2022-02-15      Social                ok

In [26]:
#7
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
print(df.columns.tolist())

['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years', 'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender', 'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text']

In [32]:
#8
import pandas as pd
df = pd.read_csv("customer_data - customer_data.csv")
print("Duplicate Customer ID Values:")
print(df.duplicated(["Customer ID"]))
print("Count of how many duplicates are existed:")
print(df.duplicated().sum())

Duplicate Customer ID Values:
0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool
Count of how many duplicates are existed:
0

In [40]:
#9
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
before = len(df)
df.drop_duplicates(subset=["Customer ID"],keep="first")
after = len(df)
print("Data shape after removing duplicates:")
print(df.shape)
print("\nDuplicate records that are removed:",before-after)

Data shape after removing duplicates:
(2000, 15)

Duplicate records that are removed: 0

In [6]:
#10
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
print("Unique values in the customer segment:")
print(df["customer_segment"].unique())
print("\nFrequency of each category:")
print(df["customer_segment"].value_counts(dropna=False))
print("\nValues showing spaces or inconsistent capitalization:")
for value in df["customer_segment"].dropna().unique():
    print(repr(value))

Unique values in the customer segment:
<StringArray>
['consumer', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.', 'UNKNOWN']
Length: 7, dtype: str

Frequency of each category:
customer_segment
Consumer      666
SMB           395
NaN           380
Enterprise    293
consumer      121
UNKNOWN        76
SMB.           69
Name: count, dtype: int64

Values showing spaces or inconsistent capitalization:
'consumer'
'Consumer'
'Enterprise'
'SMB'
'SMB.'
'UNKNOWN'

In [7]:
#11
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["customer_segment"] = (df["customer_segment"].str.strip().str.lower().str.title())
print("Customer segment after cleaning:")
print(df["customer_segment"].unique())

Customer segment after cleaning:
<StringArray>
['Consumer', 'Enterprise', 'Smb', nan, 'Smb.', 'Unknown']
Length: 6, dtype: str

In [12]:
#12
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
print("unique values in the gender column:")
print(df["gender"].unique())
df["gender"] = (df["gender"].str.strip().str.lower().replace({"m":"Male","male":"Male","f":"Female","female":"Female"}))
print("\nUnique values after cleaning:")
print(df["gender"].unique())

unique values in the gender column:
<StringArray>
[nan, 'Male', 'm', 'Female', 'M', 'F', 'f']
Length: 7, dtype: str

Unique values after cleaning:
<StringArray>
[nan, 'Male', 'Female']
Length: 3, dtype: str

In [16]:
#13
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["is_active"] = df["is_active"].replace({"Yes":1,"yes":1,"Y":1,"1":1,"No":0,"no":0,"N":0,"0":0},inplace=True)
print("is active column after cleaning:")
display(df)

is active column after cleaning:

C:\Users\hp\AppData\Local\Temp\ipykernel_9716\2336337368.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["is_active"] = df["is_active"].replace({"Yes":1,"yes":1,"Y":1,"1":1,"No":0,"no":0,"N":0,"0":0},inplace=True)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,1,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,1,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,0,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,1,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,0,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,0,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,1,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,0,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,1,No,2024-02-22,???,good

In [21]:
#14
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["churn_flag"] = df["churn_flag"].replace({"Yes":1,"No":0},inplace=True)
print("Dataset after cleaning:")
display(df)

Dataset after cleaning:

C:\Users\hp\AppData\Local\Temp\ipykernel_9716\1488614947.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["churn_flag"] = df["churn_flag"].replace({"Yes":1,"No":0},inplace=True)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,0,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,0,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,0,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,0,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,0,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,0,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,1,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,0,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,1,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,0,2024-02-22,???,good

In [23]:
#15
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
numeric_income = pd.to_numeric(df["income_usd"],errors = "coerce")
invalid_income = df[
    df["income_usd"].notna() & numeric_income.isna()
]
print("Values in income usd that cannot be interpreted as number:")
print(invalid_income["income_usd"].unique())

Values in income usd that cannot be interpreted as number:
<StringArray>
[ '$44,696',  '$41,941', '$123,682',  '$40,978',  '$45,565', '$112,864',
  '$38,946',  '$93,738',  '$70,056',  '$26,771',
 ...
  '$51,813',  '$57,778',  '$50,057', '$125,589',  '$22,832',  '$58,551',
 '$135,575',  '$34,809',  '$80,389',  '$58,046']
Length: 179, dtype: str

In [27]:
#16
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["income_usd"] = (df["income_usd"].astype(str).str.replace("$","").str.replace(",","").str.strip())
df["income_usd"] = pd.to_numeric(df["income_usd"],errors = "coerce")
print("Cleaned income_usd:")
display(df["income_usd"])

Cleaned income_usd:

0       28198.41033
1       61312.83129
2       44199.67124
3       56259.90961
4       31238.64196
           ...
1995    79436.89335
1996    39912.37991
1997    24522.26545
1998    84103.61056
1999    53723.87392
Name: income_usd, Length: 2000, dtype: float64

In [32]:
#17
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["Age"] = df["Age"].astype(str).str.extract(r"(\d+)")[0]
df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
print("Cleaned Age column:")
display(df["Age"])

Cleaned Age column:

0       45.0
1       47.0
2        NaN
3       62.0
4        NaN
        ...
1995    27.0
1996    41.0
1997    26.0
1998    42.0
1999    59.0
Name: Age, Length: 2000, dtype: float64

In [33]:
#18
import pandas as pd
import numpy as np
df = pd.read_csv('customer_data - customer_data.csv')
df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
df.loc[(df["Age"]<18) | (df["Age"]>100),"Age"]
print("Age column after replacing unrealistic values:")
display(df["Age"])

Age column after replacing unrealistic values:

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998          NaN
1999    59.256095
Name: Age, Length: 2000, dtype: float64

In [3]:
#19
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["credit Score"] = pd.to_numeric(df["credit Score"],errors = "coerce")
df["credit Score"] = (df["credit Score"].astype(str).str.strip().str.replace("pts","",regex=False))
display(df["credit Score"])

0       660.5629176
1               NaN
2       613.1327754
3       720.2369862
4       549.1832523
           ...
1995    633.9740063
1996    701.7201056
1997    647.7993363
1998            NaN
1999    576.7390735
Name: credit Score, Length: 2000, dtype: str

In [4]:
#20
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["income_usd"] = pd.to_numeric(df["income_usd"],errors = "coerce")
Q1 = df["income_usd"].quantile(0.25)
Q3 = df["income_usd"].quantile(0.75)
IQR = Q3-Q1
lower_limit = Q1-1.5*IQR
upper_limit = Q3+1.5*IQR
outliers = df[(df["income_usd"]<lower_limit) | (df["income_usd"]>upper_limit)]
print("Q1:",Q1)
print("Q3:",Q3)
print("IQR:",IQR)
print("Lower Limit:",lower_limit)
print("Upper Limit:",upper_limit)
print("\nOutliers in income usd:")
display(outliers["income_usd"])

Q1: 38370.19705
Q3: 81713.24814499999
IQR: 43343.05109499999
Lower Limit: -26644.37959249998
Upper Limit: 146727.82478749997

Outliers in income usd:

65      248156.7141
101     204783.9818
116     785035.6703
137     211200.5187
141     159459.9568
           ...
1846    327022.9582
1852    795063.7968
1914    168194.0797
1918    234262.1061
1936    258343.5457
Name: income_usd, Length: 63, dtype: float64

In [6]:
#21
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["credit Score"] = pd.to_numeric(df["credit Score"],errors = "coerce")
Q1 = df["credit Score"].quantile(0.25)
Q3 = df["credit Score"].quantile(0.75)
IQR = Q3-Q1
lower_limit = Q1-1.5*IQR
upper_limit = Q3+1.5*IQR
outliers = df[(df["credit Score"]<lower_limit) | (df["credit Score"]>upper_limit)]
print("Q1:",Q1)
print("Q3:",Q3)
print("IQR:",IQR)
print("Lower Limit:",lower_limit)
print("Upper Limit:",upper_limit)
print("\nOutliers in credit score:")
display(outliers[["credit Score"]])

Q1: 587.7191133
Q3: 708.9806484000001
IQR: 121.26153510000006
Lower Limit: 405.8268106499999
Upper Limit: 890.8729510500002

Outliers in credit score:

      credit Score
62      404.916112
348     395.344523
377     372.537221
422     162.336676
425     181.226519
446     141.922798
705     218.521526
734     362.424198
793     211.984092
877     215.344839
904     389.270475
942     240.729898
1024    195.707600
1027    151.039790
1102    216.621015
1194    225.420626
1263    393.470830
1425    356.305997
1516    280.213170
1613    248.101304
1630    261.433939
1665    179.409088
1830    332.371104

In [10]:
#22
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
suspicious_values = df[(df["tenure_years"].isin([-999,99999]))| (df["satisfaction"].isin([-999,99999]))]
display(suspicious_values[["tenure_years","satisfaction"]])

      tenure_years  satisfaction
29     -999.000000      3.391060
161   99999.000000      3.449143
358   99999.000000      2.956488
459       9.649929   -999.000000
533   99999.000000      3.083209
730       2.008998  99999.000000
788            NaN  99999.000000
894       1.206751   -999.000000
906    -999.000000      3.911122
948       3.683234  99999.000000
1136  99999.000000      3.640326
1165      5.782927  99999.000000
1421  99999.000000      3.601668
1499      2.083318   -999.000000
1627  99999.000000      5.000000
1652      4.345689   -999.000000
1657      3.909337  99999.000000
1728   -999.000000           NaN
1872      6.100963  99999.000000
1959   -999.000000      4.020120

In [12]:
#23
import pandas as pd
import numpy as np
df = pd.read_csv('customer_data - customer_data.csv')
df["tenure_years"] = (df["tenure_years"].replace([-999,99999],np.nan))
df["satisfaction"] = (df["satisfaction"].replace([-999,99999],np.nan))
display(df[["tenure_years","satisfaction"]])

      tenure_years  satisfaction
0         5.274076      3.382150
1         5.632826           NaN
2              NaN      4.195157
3         2.029634           NaN
4         2.648626      3.117326
...            ...           ...
1995     14.007477      3.556073
1996      0.673289      2.963094
1997      2.026485      3.079259
1998      7.168156      3.579652
1999      9.720663      1.100520

[2000 rows x 2 columns]

In [17]:
#24
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
numeric_columns = df.select_dtypes(include="number").columns
for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())
display(df[numeric_columns])

      tenure_years  monthly_visits  satisfaction
0         5.274076             5.0      3.382150
1         5.632826             9.0      3.743458
2         4.688777             8.0      4.195157
3         2.029634             4.0      3.743458
4         2.648626             5.0      3.117326
...            ...             ...           ...
1995     14.007477             6.0      3.556073
1996      0.673289             8.0      2.963094
1997      2.026485            12.0      3.079259
1998      7.168156             5.0      3.579652
1999      9.720663             6.0      1.100520

[2000 rows x 3 columns]

In [19]:
#25
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
categorical_columns = df.select_dtypes(include='object').columns
for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode())
display(df[categorical_columns])

C:\Users\hp\AppData\Local\Temp\ipykernel_23800\487166177.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include='object').columns

,Customer ID,Age,income_usd,credit Score,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,Pune,consumer,m,Yes,No,2026-03-11,Referral,normal
1,CUST-00354,47.76516428,61312.83129,838 pts,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [20]:
#26
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["signup_date"] = pd.to_datetime(df["signup_date"],errors = "coerce")
display(df["signup_date"])

0      2026-03-11
1             NaT
2      2024-09-20
3      2023-07-12
4      2024-08-06
          ...
1995   2024-02-26
1996   2024-08-11
1997   2023-05-27
1998   2025-01-26
1999   2024-02-22
Name: signup_date, Length: 2000, dtype: datetime64[us]

In [ ]:
#27
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
invalid_dates = df[df["signup_date"].isna()]
display(invalid_dates)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
14,CUST-00375,NaN,45252.12673,823.0997611,3.461954,4.0,4.026637,Delhi,Consumer,M,NaN,No,NaN,NaN,ok
16,CUST-00747,59.57113427,97774.31584,649.7892751,2.256617,8.0,3.493731,Hyderabad,SMB.,M,Yes,No,NaN,Unknown,normal
24,CUST-01923,NaN,NaN,NaN,6.988777,7.0,5.000000,Mumbai,Enterprise,NaN,yes,No,NaN,email,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960,CUST-00475,NaN,33386.23058,652.6752196,5.599846,6.0,3.776814,Mumbai,Enterprise,M,Y,Yes,NaN,google_ads,NaN
1964,CUST-00253,NaN,79731.3412,NaN,3.158138,6.0,NaN,Pune,Consumer,f,0,No,NaN,Email,complaint!!!
1974,CUST-01438,18,58115.15575,547.1562386,7.262657,NaN,4.135724,Mumbai,Consumer,Female,N,Yes,NaN,NaN,NaN
1983,CUST-01124,35.17004765,74269.07836,703.5642206,NaN,7.0,3.486785,Pune,SMB.,f,0,No,NaN,NaN,normal
1988,CUST-01239,45.4 years,90683.09594,719.9143795,7.362245,9.0,4.418195,NaN,Enterprise,Male,Y,No,NaN,Referral,good

In [3]:
#28
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
df["lead_source"] = (df["lead_source"].astype(str).str.strip().str.lower().replace({"Website":"Website","website":"Website","WEB":"Website","Referral":"Referral","referral":"Referral","Google Ads":"Google Ads","google_ads":"Google Ads","email":"Email","web":"Website"}))
display(df[["lead_source"]])

     lead_source
0       Referral
1        Website
2          Email
3        Website
4            NaN
...          ...
1995       Email
1996     Website
1997     Website
1998       Email
1999         ???

[2000 rows x 1 columns]

In [ ]:
#30
import pandas as pd
df = pd.read_csv('customer_data - customer_data.csv')
print("Missing values:")
print(df.isnull().sum())
print("\nDuplicate rows:")
print(df.duplicated().sum())
print("\nDuplicate customer id's:")
print(df.duplicated("Customer ID").sum())
print("\ncheck data types:")
print(df.dtypes)

Missing values:
Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

Duplicate rows:
0

Duplicate customer id's:
19

check data types:
Customer ID             str
Age                     str
income_usd              str
credit Score            str
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                    str
customer_segment        str
gender                  str
is_active               str
churn_flag              str
signup_date             str
lead_source             str
notes_text              str
dtype: object