In [1]:
#1
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [2]:
#2
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
#3
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.sample(n=7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4773,4774,15709451,Gordon,646,Germany,Female,35,1,121952.75,2,1,1,142839.82,0
909,910,15693814,Niu,806,Spain,Male,25,7,0.00,2,1,0,18461.90,0
6033,6034,15759966,Chiemenam,612,Spain,Female,36,5,119799.27,2,1,0,159416.58,0
353,354,15812007,Power,670,Spain,Male,25,6,0.00,2,1,1,78358.94,0
3580,3581,15634359,Dyer,639,Germany,Female,41,5,98635.77,1,1,0,199970.74,0
3293,3294,15691863,Cody,751,France,Female,39,3,0.00,2,1,1,84175.34,0
1278,1279,15641690,Hsiao,681,Spain,Male,67,7,0.00,2,0,1,163714.92,0

In [4]:
#4
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [6]:
#5
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.isna()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
#6
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.select_dtypes(include=["int"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='str')

In [12]:
#7
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [15]:
#8
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
print("DF Duplicated:",df.duplicated())
print("Droping Duplicates:",df.drop_duplicates())

DF Duplicated: 0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool
Droping Duplicates:       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]

In [21]:
#9
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df_drop = df.drop_duplicates()
print("Original rows: ", len(df))
print("After removing duplicates: ", len(df_drop))
print("Duplicates removed: ", len(df) - len(df_drop))
df_drop.to_csv('Cleaned_dataset.csv', index=False)
print("Saved cleaned dataset as Cleaned_dataset.csv")

Original rows:  10000
After removing duplicates:  10000
Duplicates removed:  0
Saved cleaned dataset as Cleaned_dataset.csv

In [27]:
#10
import pandas as pd
df = pd.read_csv("Bank_customer_churn - Bank_customer_churn.csv")
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [28]:
#11
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"})

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [33]:
#12
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.add_prefix("Bank_")

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [42]:
#13
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df['Age']=df['Age'].astype(float)
print(df.dtypes)

RowNumber            int64
CustomerId           int64
Surname                str
CreditScore          int64
Geography              str
Gender                 str
Age                float64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [46]:
#14
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df["Exited"] = df["Exited"].astype(str)
print(df.dtypes)

RowNumber            int64
CustomerId           int64
Surname                str
CreditScore          int64
Geography              str
Gender                 str
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited                 str
dtype: object

In [ ]:
#15
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df['Balance'].fillna(df['Balance'].mean(), inplace=True)

Balance mean: 76485.889288
Missing Balance values before replacement: 0
Missing Balance values after replacement: 0

In [57]:
#16
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df["Age"].fillna(df["Age"].median(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5300\1755239223.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Age"].fillna(df["Age"].median(),inplace=True)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [59]:
#17
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"},inplace=True)
df.head(5)

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [1]:
#18
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)
df.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [2]:
#19
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.drop(columns=['Geography'],inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Gender           10000 non-null  str
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(2)
memory usage: 1015.8 KB

In [3]:
#20
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.rename(columns={'NumOfProducts':"Products","HasCrCard":"CreditCard"},inplace=True)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
#21
import pandas as pd
df = pd.read_csv("Bank_customer_churn - Bank_customer_churn.csv")
df.rename(columns={"RowNumber":"Row_No","CustomerId":"Customer_ID","Surname":"Last_Name","CreditScore":"Credit_Score","Geography":"Country","Gender":"Sex","EstimatedSalary":"Salary","Exited":"Target"},inplace=True)
df.head()

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Sex,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [17]:
#22
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df_num = df.select_dtypes(include=['number'])
df_describe = df_num.describe()
print(df_describe)

         RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000
mean    76485.889288       1.530200      0.70550        0.515100
std     62397.405202       0.581654      0.45584        0.499797
min         0.000000       1.000000      0.00000        0.000000
25%         0.000000       1.000000      0.00000        0.000000
50%     97198.540000       1.000000      1.00000        1.000000
75%    127644.240000       2.000000      1.00000        1.000000
max    250898.090000       4.000000      1.00000        1.000000

       EstimatedSalary        Exited
count     10000.000000  10000.000000
mean     100090.239881      0.203700
std       57510.492818      0.402769
min          11.580000      0.000000
25%       51002.110000      0.000000
50%      100193.915000      0.000000
75%      149388.247500      0.000000
max      199992.480000      1.000000

In [21]:
#23
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
duplicate_count = df.duplicated().sum()
print("Number of duplicate records found: ",duplicate_count)
df_cleaned = df.drop_duplicates()
print("\n  DataSet information after cleaning   ")
print(df_cleaned.info())

Number of duplicate records found:  0

  DataSet information after cleaning
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB
None

In [25]:
#24
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df.add_prefix('Customer_')

,Customer_RowNumber,Customer_CustomerId,Customer_Surname,Customer_CreditScore,Customer_Geography,Customer_Gender,Customer_Age,Customer_Tenure,Customer_Balance,Customer_NumOfProducts,Customer_HasCrCard,Customer_IsActiveMember,Customer_EstimatedSalary,Customer_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [32]:
#25
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df_prefix = df.add_prefix('Customer_')
df_convert = df_prefix.astype({
    'Customer_Age':'float64',
    'Customer_Balance':'float64',
    'Customer_EstimatedSalary':'float64'
})
df_convert.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_RowNumber        10000 non-null  int64
 1   Customer_CustomerId       10000 non-null  int64
 2   Customer_Surname          10000 non-null  str
 3   Customer_CreditScore      10000 non-null  int64
 4   Customer_Geography        10000 non-null  str
 5   Customer_Gender           10000 non-null  str
 6   Customer_Age              10000 non-null  float64
 7   Customer_Tenure           10000 non-null  int64
 8   Customer_Balance          10000 non-null  float64
 9   Customer_NumOfProducts    10000 non-null  int64
 10  Customer_HasCrCard        10000 non-null  int64
 11  Customer_IsActiveMember   10000 non-null  int64
 12  Customer_EstimatedSalary  10000 non-null  float64
 13  Customer_Exited           10000 non-null  int64
dtypes: float64(3), int64(8), str(3)
memory usage: 1.1 MB

In [34]:
#26
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df["CreditScore"].fillna(df['CreditScore'].median())

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [37]:
#27
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df_median = df["EstimatedSalary"].fillna(df["EstimatedSalary"].mean())
df_median.head(8)

0    101348.88
1    112542.58
2    113931.57
3     93826.63
4     79084.10
5    149756.71
6     10062.80
7    119346.88
Name: EstimatedSalary, dtype: float64

In [41]:
#28
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df_remove = df.drop_duplicates()
df_rename = df_remove.rename(columns={"Exited":"Target"})
df_convert = df_rename["Target"].astype(str)
df_info = df_convert.info()
print("DF Removed Duplicate rows: ",df_remove)
print("DF Remove: ",df_rename)
print("Df Convert: ",df_convert)
print("Df Info: ",df_info)

<class 'pandas.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: Target
Non-Null Count  Dtype
--------------  -----
10000 non-null  str
dtypes: str(1)
memory usage: 78.3 KB
DF Removed Duplicate rows:        RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
DF Remove:        RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Target
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
Df Convert:  0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Target, Length: 10000, dtype: str
Df Info:  None

In [51]:
#29
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df_renaming  = df.rename(columns={'Gender':'CustomerGender',"Geography":"Country"})
df_renaming_prefix = df_renaming.add_prefix('Bank_')
df_drop = df_renaming_prefix.drop(columns=['Bank_RowNumber'])
df_drop.head(10)

,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Country,Bank_CustomerGender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [53]:
#30
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
print("Displaying dataset: ",df)
print("check missing values: ",df.isnull().sum())
df_remove = df.drop_duplicates()
df_rename = df_remove.rename(columns={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","Estimated_Salary":"Salary","Exited":"Target"})
df_convert = df_rename.astype({"Age":"float64","Balance":"float64","Target":"string"})
df_convert["Age"] = df_convert["Age"].fillna(df_convert["Age"].median())
df_convert["Balance"] = df_convert["Balance"].fillna(df_convert["Balance"].mean())
df_remove_columns = df_convert.drop(columns=['RowNumber','Surname'])
print("Display first 10 rows: ",df_remove_columns.head(10))
print("Statistical summary: ",df_remove_columns.describe())
print("Value counts of target: ",df_remove_columns["Target"].value_counts())
print("Final DataSet Information: ",df_remove_columns.info())

Displaying dataset:        RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]
check missing values:  RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
Display first 10 rows:     Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82
5     15574012           645     Spain    Male  44.0       8  113755.78
6     15592531           822    France    Male  50.0       7       0.00
7     15656148           376   Germany  Female  29.0       4  115046.74
8     15792365           501    France    Male  44.0       4  142051.07
9     15592389           684    France    Male  27.0       2  134603.88

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary Target
0              1          1               1        101348.88      1
1              1          0               1        112542.58      0
2              3          1               0        113931.57      1
3              2          0               0         93826.63      0
4              1          1               1         79084.10      0
5              2          1               0        149756.71      1
6              2          1               1         10062.80      0
7              4          1               0        119346.88      1
8              2          0               1         74940.50      0
9              1          1               1         71725.73      0
Statistical summary:          Customer_ID  Credit_Score           Age        Tenure        Balance  \
count  1.000000e+04  10000.000000  10000.000000  10000.000000   10000.000000
mean   1.569094e+07    650.528800     38.921800      5.012800   76485.889288
std    7.193619e+04     96.653299     10.487806      2.892174   62397.405202
min    1.556570e+07    350.000000     18.000000      0.000000       0.000000
25%    1.562853e+07    584.000000     32.000000      3.000000       0.000000
50%    1.569074e+07    652.000000     37.000000      5.000000   97198.540000
75%    1.575323e+07    718.000000     44.000000      7.000000  127644.240000
max    1.581569e+07    850.000000     92.000000     10.000000  250898.090000

       NumOfProducts    HasCrCard  IsActiveMember  EstimatedSalary
count   10000.000000  10000.00000    10000.000000     10000.000000
mean        1.530200      0.70550        0.515100    100090.239881
std         0.581654      0.45584        0.499797     57510.492818
min         1.000000      0.00000        0.000000        11.580000
25%         1.000000      0.00000        0.000000     51002.110000
50%         1.000000      1.00000        1.000000    100193.915000
75%         2.000000      1.00000        1.000000    149388.247500
max         4.000000      1.00000        1.000000    199992.480000
Value counts of target:  Target
0    7963
1    2037
Name: count, dtype: Int64
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      10000 non-null  int64
 1   Credit_Score     10000 non-null  int64
 2   Geography        10000 non-null  str
 3   Gender           10000 non-null  str
 4   Age              10000 non-null  float64
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Target           10000 non-null  string
dtypes: float64(3), int64(6), str(2), string(1)
memory usage: 937.6 KB
Final DataSet Information:  None

In [55]:
#B1
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df['TotalMoney'] = df['Balance'] + df["EstimatedSalary"]
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,TotalMoney
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,101348.88
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,196350.44
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,273592.37
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,93826.63
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,204594.92
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,263512.49
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,10062.80
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,234393.62
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,216991.57
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,206329.61

In [56]:
#B2
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df['DoubleScore'] = df["CreditScore"]*2
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,DoubleScore
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1238
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1216
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1004
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1398
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1700
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,1290
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,1644
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,752
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,1002
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,1368

In [57]:
#B3
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df["AgeAfter10Years"] = df["Age"]+10
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,AgeAfter10Years
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,52
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,51
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,52
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,49
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,53
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,54
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,60
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,39
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,54
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,37

In [58]:
#B4
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df['HasBalance'] = df["Balance"]
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,HasBalance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,83807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,159660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,125510.82
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,113755.78
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,0.00
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,115046.74
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,142051.07
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,134603.88

In [59]:
#B5
import pandas as pd
df = pd.read_csv('Bank_customer_churn - Bank_customer_churn.csv')
df["SalaryInLakhs"] = df["EstimatedSalary"]/100000
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,SalaryInLakhs
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1.013489
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1.125426
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1.139316
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.938266
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0.790841
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,1.497567
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,0.100628
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,1.193469
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,0.749405
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,0.717257