In [9]:
#1
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
print("Loading the dataset: ")
display(df)
print("Display dataset information: ")
df.info()
print("\nDataset Information: ")
df.info()
print("\nMissing Values: ")
display(df.isnull().sum())
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df = df.rename(columns={"Target":"CustomerStatus","AnnualIncome":"Income"})
print("\nFirst 15 rows: ")
display(df.head(15))

Loading the dataset:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Display dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

Missing Values:

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

First 15 rows:

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [18]:
#2
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
print("Select only numeric columns: ")
display(df.select_dtypes(include=['number']))
print("Displaying Summary Statistics: ")
display(df.describe())
print("After converting Age and Credit score to float: ")
print(df.astype({"Age":"float64","CreditScore":"float64"}))
print("Displaying information again: ")
df.info()

Select only numeric columns:

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0          10001  58.0       49184.0      2139          581        NaN       2
1          10002  65.0      162964.0      6197          732    6356.54       1
2          10003  56.0       26956.0     37281          503  143203.92       8
3          10004  55.0       92926.0       925          463  139627.88       5
4          10005  66.0      108236.0      7198          394   75985.46       5
...          ...   ...           ...       ...          ...        ...     ...
1015       10450  43.0      173620.0      7121          644   60353.03       2
1016       10753  25.0       54490.0     13794          303  124512.07       4
1017       10810  49.0       82062.0     47170          813   53850.09       8
1018       10267  38.0           NaN     10424          722  138100.05       6
1019       10059  62.0       97504.0     36833          430        NaN      10

[1020 rows x 7 columns]

Displaying Summary Statistics:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

After converting Age and Credit score to float:
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
0          10001  58.0       49184.0      2139        581.0        NaN
1          10002  65.0      162964.0      6197        732.0    6356.54
2          10003  56.0       26956.0     37281        503.0  143203.92
3          10004  55.0       92926.0       925        463.0  139627.88
4          10005  66.0      108236.0      7198        394.0   75985.46
...          ...   ...           ...       ...          ...        ...
1015       10450  43.0      173620.0      7121        644.0   60353.03
1016       10753  25.0       54490.0     13794        303.0  124512.07
1017       10810  49.0       82062.0     47170        813.0   53850.09
1018       10267  38.0           NaN     10424        722.0  138100.05
1019       10059  62.0       97504.0     36833        430.0        NaN

      Tenure Geography  Gender    Segment Target
0          2    France    Male        SME   Stay
1          1       USA    Male        SME  Churn
2          8    Canada    Male  Corporate   Stay
3          5       NaN    Male     Retail  Churn
4          5        UK   Other  Corporate  Churn
...      ...       ...     ...        ...    ...
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn

[1020 rows x 11 columns]
Displaying information again:
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

In [22]:
#3
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
print("Counting Duplicate rows: ")
print(df.duplicated().sum())
print("\nInformation before removing duplicates: ")
df.info()
df = df.drop_duplicates()
print("\nInformation after removing duplicates: ")
df.info()
print("\nDisplaying last 20 rows: ")
display(df.tail(20))

Counting Duplicate rows:
20

Information before removing duplicates:
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

Information after removing duplicates:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    str
 8   Gender        950 non-null    str
 9   Segment       950 non-null    str
 10  Target        1000 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 86.1 KB

Displaying last 20 rows:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
980,10981,41.0,199633.0,8498,847,173390.59,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541,59484.58,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334,NaN,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732,175352.25,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730,120423.19,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488,126031.27,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621,115161.87,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720,158528.46,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635,159905.73,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884,44897.43,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773,39653.24,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452,17812.25,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764,165451.49,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594,149288.61,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493,83666.20,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [ ]:
#4
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df_renaming = df.rename(columns={"CustomerID":"Employee_ID","Age":"EmployeeAge","Gender":"EmployeeGender","AnnualIncome":"Salary","Target":"PromotionStatus"})
df_adding_prefix = df_renaming.add_prefix("HR_")
display(df_adding_prefix.sample(n=10))

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
473,10474,43.0,164717.0,21873,582,103937.64,0,France,Other,SME,Churn
599,10600,31.0,59384.0,12749,461,72444.59,1,France,Male,Corporate,Churn
124,10125,30.0,82601.0,37973,692,46712.49,6,India,Female,SME,Stay
490,10491,40.0,140323.0,17014,523,93339.60,10,Germany,Other,Corporate,Stay
976,10977,24.0,65915.0,14531,581,87895.08,4,Germany,Male,Corporate,Stay
967,10968,66.0,98715.0,29033,720,63730.64,1,France,Male,Corporate,Churn
769,10770,69.0,29321.0,42813,439,96299.10,10,Canada,Other,Corporate,Churn
725,10726,63.0,25633.0,3105,553,184454.02,4,UK,Female,Corporate,Stay
939,10940,25.0,57582.0,26374,710,139007.42,1,France,Male,Retail,Churn
806,10807,64.0,147585.0,43617,747,NaN,2,India,Male,SME,Stay

In [5]:
#5
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].fillna(df["Age"].median())
display(df.describe())

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [11]:
#6
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(2), int64(5), str(4)
memory usage: 87.8 KB

In [16]:
#7
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df.drop(columns=["Segment","Geography"])
df.drop_duplicates()
display(df.head(10))
df.info()
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [29]:
#8
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df.drop_duplicates()
df_drop = df.drop(columns=["CustomerID","Segment"])
df_renaming = df_drop.rename(columns={"Target":"Output"})
print(df_renaming.head())
print(df_renaming.info())
print(df_renaming.describe())
print(df_renaming["Output"].value_counts())

    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
0  58.0       49184.0      2139          581        NaN       2    France
1  65.0      162964.0      6197          732    6356.54       1       USA
2  56.0       26956.0     37281          503  143203.92       8    Canada
3  55.0       92926.0       925          463  139627.88       5       NaN
4  66.0      108236.0      7198          394   75985.46       5        UK

  Gender Output
0   Male   Stay
1   Male  Churn
2   Male   Stay
3   Male  Churn
4  Other  Churn
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           970 non-null    float64
 1   AnnualIncome  967 non-null    float64
 2   Spending      1020 non-null   int64
 3   CreditScore   1020 non-null   int64
 4   Balance       969 non-null    float64
 5   Tenure        1020 non-null   int64
 6   Geography     969 non-null    str
 7   Gender        968 non-null    str
 8   Output        1020 non-null   str
dtypes: float64(3), int64(3), str(3)
memory usage: 71.8 KB
None
              Age   AnnualIncome      Spending  CreditScore        Balance  \
count  970.000000     967.000000   1020.000000  1020.000000     969.000000
mean    44.249485  112505.928645  25232.615686   602.659804   97523.535666
std     15.521935   52303.362541  14219.393105   176.560690   55796.562543
min     18.000000   20227.000000    537.000000   300.000000     547.600000
25%     30.250000   66149.000000  13134.750000   440.750000   50077.860000
50%     44.000000  112358.000000  24798.000000   607.000000   95100.060000
75%     58.000000  158000.500000  37956.000000   757.250000  143947.810000
max     70.000000  199967.000000  49995.000000   900.000000  199885.880000

            Tenure
count  1020.000000
mean      5.261765
std       3.185330
min       0.000000
25%       2.000000
50%       5.000000
75%       8.000000
max      10.000000
Output
Churn    515
Stay     505
Name: count, dtype: int64

In [30]:
#9
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df["Networth"] = df["Balance"] + df["AnnualIncome"]
df["AgeAfterRetirement"] = df["Age"] + 20
df["DoubleCreditScore"] = df["CreditScore"]*2
df["IncomePerMonth"] = df["AnnualIncome"]/12
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Networth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

In [40]:
#10
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
print("First Five rows: ")
display(df.head())
print("\nLast five rows: ")
display(df.tail())
print("\nTen random rows: ")
display(df.sample(n=10))
print("\nDataset information: ")
df.info()
print("\nDescriptive Statistics: ")
display(df.describe())
df_renaming = df.rename(columns={"Target":"Customer_Status"})
print("After renaming: ")
display(df_renaming)

First Five rows:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

Last five rows:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Ten random rows:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
424,10425,55.0,45054.0,33623,436,127443.14,6,India,Other,SME,Churn
624,10625,60.0,123584.0,27071,900,40062.08,0,France,Other,Retail,Churn
697,10698,NaN,67289.0,36542,711,100938.56,10,USA,Other,SME,Stay
920,10921,NaN,57674.0,1345,440,103634.15,5,Canada,Female,Corporate,Churn
255,10256,48.0,94907.0,35672,308,169434.47,6,USA,Female,SME,Churn
450,10451,68.0,187579.0,32429,624,34840.53,8,France,Other,Corporate,Stay
691,10692,32.0,178847.0,47544,372,2617.22,3,France,Female,Retail,Churn
646,10647,62.0,62819.0,4434,520,162763.61,7,France,Male,Corporate,Stay
162,10163,47.0,152527.0,40177,740,19835.69,1,France,Other,SME,Churn
484,10485,41.0,141692.0,33603,706,127081.96,1,France,Male,Retail,Churn

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

Descriptive Statistics:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

After renaming:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [44]:
#11
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
print("Total Missing Values: ")
display(df.isnull().sum())
print("\nNumerical columns: ")
df.select_dtypes(include=["number"]).columns
print("Mean of Balance: ",df["Balance"].mean())
print("Median Of age: ",df["Age"].median())
df.fillna(0)
df.info()

Total Missing Values:

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

Numerical columns:
Mean of Balance:  97523.53566563467
Median Of age:  44.0
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB

In [ ]:
#12
import pandas as pd
from IPython.display import display
df = pd.read_csv('Task_dataset - Task_dataset.csv')
print("Count of stay and churn: ",df["Target"].value_counts())
df_renaming = df.rename(columns={"Target":"Customer_Class"})
df_change_dtype = df_renaming["Customer_Class"].astype(str)

Count of stay and churn:  Target
Churn    515
Stay     505
Name: count, dtype: int64

411    Churn
427    Churn
569    Churn
591    Churn
452    Churn
719     Stay
284    Churn
886     Stay
105     Stay
876    Churn
Name: Customer_Class, dtype: str

In [4]:
#13
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df_renaming = df.rename(columns={"Balance":"AccountBalance","AnnualIncome":"Salary","CreditScore":"Score"})
df_adding_prefix = df_renaming.add_prefix("Sales_")
df_adding_prefix.sample(n=20)

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
791,10792,47.0,64774.0,18998,656,120888.05,2,Germany,Male,Corporate,Stay
399,10400,23.0,85055.0,36767,591,155793.93,0,NaN,Female,Retail,Churn
471,10472,69.0,70521.0,8769,343,84674.98,10,Canada,NaN,SME,Churn
898,10899,43.0,150919.0,10027,769,185562.26,2,India,Other,SME,Stay
327,10328,47.0,168111.0,16438,531,59994.93,1,France,Other,Retail,Churn
950,10951,61.0,148595.0,43758,867,137074.83,9,Canada,Female,SME,Stay
737,10738,48.0,190280.0,25007,488,170425.89,7,Canada,Male,Retail,Churn
558,10559,42.0,30652.0,28582,585,111319.72,2,USA,Other,Corporate,Stay
228,10229,45.0,91973.0,42408,358,15008.23,10,Canada,Female,SME,Churn
814,10815,39.0,130366.0,23628,601,57841.69,0,NaN,Other,SME,Churn
419,10420,57.0,83591.0,30903,677,118338.19,7,USA,Other,SME,Stay
533,10534,53.0,188641.0,25314,712,163420.66,1,Canada,NaN,SME,Churn
336,10337,53.0,118415.0,28801,490,135938.97,10,Canada,Male,SME,Churn
554,10555,50.0,95402.0,45912,348,185296.96,6,Canada,Other,Corporate,Churn
159,10160,59.0,28165.0,4486,790,NaN,6,France,Male,Corporate,Stay
619,10620,56.0,134131.0,6276,365,52618.40,5,India,Other,Retail,Churn
729,10730,58.0,199967.0,15404,727,48072.16,2,Canada,Female,SME,Stay
435,10436,21.0,64037.0,38110,743,164337.08,6,Canada,Male,Corporate,Stay
790,10791,39.0,105134.0,30206,799,6052.83,7,India,Female,NaN,Churn
129,10130,63.0,147912.0,35956,336,123491.89,3,France,Other,Corporate,Churn

In [13]:
#14
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df.drop_duplicates(inplace=True)
df.rename(columns={"Target":"Exited"},inplace=True)
df.fillna({
    "Age": 0,
    "AnnualIncome": 0,
    "Spending": 0,
    "CreditScore": 0,
    "Balance": 0,
    "Tenure": 0,
    "Geography": "Unknown",
    "Gender": "Unknown",
    "Segment": "Unknown"
}, inplace=True)
df["Balance"] = df["Balance"].astype(float)
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,42.002000,106835.388000,25285.558000,603.088000,92679.687490,5.241000
std,288.819436,17.941123,56662.551688,14211.735656,176.605486,58439.408092,3.179155
min,10001.000000,0.000000,0.000000,537.000000,300.000000,0.000000,0.000000
25%,10250.750000,28.000000,60393.750000,13213.000000,441.000000,43913.355000,2.000000
50%,10500.500000,43.000000,107245.000000,24901.000000,606.500000,92217.615000,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [17]:
#15
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df_numeric = df.select_dtypes(include=["number"])
display(df_numeric)
df_numeric = df_numeric.drop(columns=["CustomerID"])
print("Statistical Summary: ")
df_numeric.describe()

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0          10001  58.0       49184.0      2139          581        NaN       2
1          10002  65.0      162964.0      6197          732    6356.54       1
2          10003  56.0       26956.0     37281          503  143203.92       8
3          10004  55.0       92926.0       925          463  139627.88       5
4          10005  66.0      108236.0      7198          394   75985.46       5
...          ...   ...           ...       ...          ...        ...     ...
1015       10450  43.0      173620.0      7121          644   60353.03       2
1016       10753  25.0       54490.0     13794          303  124512.07       4
1017       10810  49.0       82062.0     47170          813   53850.09       8
1018       10267  38.0           NaN     10424          722  138100.05       6
1019       10059  62.0       97504.0     36833          430        NaN      10

[1020 rows x 7 columns]

Statistical Summary:

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [19]:
#16
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df.drop_duplicates(inplace=True)
df.fillna({
    "Age": 0,
    "AnnualIncome": 0,
    "Spending": 0,
    "CreditScore": 0,
    "Balance": 0,
    "Tenure": 0,
    "Geography": "Unknown",
    "Gender": "Unknown",
    "Segment": "Unknown"
}, inplace=True)
df["Balance"] = df["Balance"].astype(float)
df.rename(columns={"Target":"CustomerStatus"},inplace=True)
print("First 10 rows: ")
print(df.head(10))
print("\nDataset Information:")
df.info()

First 10 rows:
   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581       0.00       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5
5       10006  69.0       31390.0     48323          770  107245.62       6
6       10007  58.0      182141.0     24200          891   38457.72       1
7       10008  67.0       95861.0      5729          538  173296.73       6
8       10009  41.0       62638.0     24760          663   41901.41       4
9       10010  22.0      179680.0     42113          475  106827.98       3

  Geography  Gender    Segment CustomerStatus
0    France    Male        SME           Stay
1       USA    Male        SME          Churn
2    Canada    Male  Corporate           Stay
3   Unknown    Male     Retail          Churn
4        UK   Other  Corporate          Churn
5     India   Other  Corporate           Stay
6     India   Other     Retail          Churn
7        UK  Female        SME           Stay
8    France   Other        SME           Stay
9       USA  Female  Corporate          Churn

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1000 non-null   int64
 1   Age             1000 non-null   float64
 2   AnnualIncome    1000 non-null   float64
 3   Spending        1000 non-null   int64
 4   CreditScore     1000 non-null   int64
 5   Balance         1000 non-null   float64
 6   Tenure          1000 non-null   int64
 7   Geography       1000 non-null   str
 8   Gender          1000 non-null   str
 9   Segment         1000 non-null   str
 10  CustomerStatus  1000 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 86.1 KB

In [21]:
#17
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df.drop_duplicates(inplace=True)
df.fillna({
    "Age": df["Age"].median(),
    "AnnualIncome": df["AnnualIncome"].mean(),
    "Spending": df["Spending"].mean(),
    "CreditScore": df["CreditScore"].mean(),
    "Balance": df["Balance"].mean(),
    "Tenure": df["Tenure"].median(),
    "Geography": "Unknown",
    "Gender": "Unknown",
    "Segment": "Unknown"
}, inplace=True)
df.rename(columns={
    "CustomerID": "Customer_ID",
    "Age": "Customer_Age",
    "AnnualIncome": "Annual_Income",
    "Spending": "Customer_Spending",
    "CreditScore": "Credit_Score",
    "Balance": "Account_Balance",
    "Tenure": "Customer_Tenure",
    "Geography": "Country",
    "Gender": "Gender",
    "Segment": "Customer_Segment",
    "Target": "Customer_Status"
}, inplace=True)
df.add_prefix("Company")
print("Statistical Summary: ")
display(df.describe())
print("\nTarget Counts:")
display(df["Customer_Status"].value_counts())

Statistical Summary:

,Customer_ID,Customer_Age,Annual_Income,Customer_Spending,Credit_Score,Account_Balance,Customer_Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112458.303158,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.475249,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112458.303158,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

Target Counts:

Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [29]:
#18
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
mean_balance = df["Balance"].mean()
median_balance = df["Balance"].median()
mean_age = df["Age"].mean()
median_annualincome = df["AnnualIncome"].median()
print("Mean Balance:", mean_balance)
print("Median Balance:", median_balance)
print("Mean Age:", mean_age)
print("Median AnnualIncome:", median_annualincome)
df["Balance"] = df["Balance"].fillna(mean_balance)
df["Age"] = df["Age"].fillna(mean_age)
df["AnnualIncome"] = df["AnnualIncome"].fillna(median_annualincome)
print("\nAfter filling missing values: ")
df

Mean Balance: 97523.53566563467
Median Balance: 95100.06
Mean Age: 44.24948453608248
Median AnnualIncome: 112358.0

After filling missing values:

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.030000,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.070000,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.090000,8,Germany,Female,Retail,Stay
1018,10267,38.0,112358.0,10424,722,138100.050000,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,97523.535666,10,Canada,Other,NaN,Churn

In [31]:
#19
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df["Income_in_Lakhs"] = df["AnnualIncome"]/100000
df["Balance_in_Lakhs"] = df["Balance"]/100000
df["SeniorCitizen"] = df["Age"]+0
df["HighCreditScore"] = df["CreditScore"]*1
df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,0.49184,NaN,58.0,581
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,0.31390,1.072456,69.0,770
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,1.82141,0.384577,58.0,891
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,0.95861,1.732967,67.0,538
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,0.62638,0.419014,41.0,663
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,1.79680,1.068280,22.0,475

In [32]:
#20
import pandas as pd
df = pd.read_csv('Task_dataset - Task_dataset.csv')
df.info()
print("Find Missing Values: ",df.isnull().sum())
df.drop_duplicates(inplace=True)
df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Income",
    "CreditScore": "Credit_Score",
    "Target": "CustomerStatus"
}, inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median().astype(int))
df["Income"] = df["Income"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Income"] = df["Income"].fillna(df["Income"].mean())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.drop(columns=["Segment","Customer_ID"],inplace=True)
df["TotalMoney"] = df["Balance"] + df["Income"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["Income"] / 12
df["CreditScoreDouble"] = df["Credit_Score"] * 2
print("\nFirst 10 Rows:")
display(df.head(10))
print("\nLast 10 Rows:")
display(df.tail(10))
print("\n10 Random Rows:")
display(df.sample(10))
print("\nStatistical Summary:")
display(df.describe())
print("\nTarget Counts:")
display(df["CustomerStatus"].value_counts())
print("\nFinal Dataset Information:")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
Find Missing Values:  CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

First 10 Rows:

,Age,Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,CustomerStatus,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
0,58.0,49184.0,2139,581,97557.565779,2,France,Male,Stay,146741.565779,63.0,4098.666667,1162
1,65.0,162964.0,6197,732,6356.540000,1,USA,Male,Churn,169320.540000,70.0,13580.333333,1464
2,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Stay,170159.920000,61.0,2246.333333,1006
3,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Churn,232553.880000,60.0,7743.833333,926
4,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Churn,184221.460000,71.0,9019.666667,788
5,69.0,31390.0,48323,770,107245.620000,6,India,Other,Stay,138635.620000,74.0,2615.833333,1540
6,58.0,182141.0,24200,891,38457.720000,1,India,Other,Churn,220598.720000,63.0,15178.416667,1782
7,67.0,95861.0,5729,538,173296.730000,6,UK,Female,Stay,269157.730000,72.0,7988.416667,1076
8,41.0,62638.0,24760,663,41901.410000,4,France,Other,Stay,104539.410000,46.0,5219.833333,1326
9,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Churn,286507.980000,27.0,14973.333333,950

Last 10 Rows:

,Age,Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,CustomerStatus,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
990,58.0,79954.000000,6331,773,39653.24,2,India,Female,Stay,119607.240000,63.0,6662.833333,1546
991,45.0,112458.303158,17549,452,17812.25,5,USA,Other,Churn,130270.553158,50.0,9371.525263,904
992,18.0,157845.000000,29018,764,165451.49,7,India,Male,Stay,323296.490000,23.0,13153.750000,1528
993,31.0,69950.000000,17945,594,149288.61,6,USA,Female,Stay,219238.610000,36.0,5829.166667,1188
994,56.0,76509.000000,19044,493,83666.20,6,USA,Male,Churn,160175.200000,61.0,6375.750000,986
995,34.0,81731.000000,40980,761,181465.65,5,Germany,Other,Stay,263196.650000,39.0,6810.916667,1522
996,47.0,42475.000000,1176,780,26640.99,5,France,Female,Stay,69115.990000,52.0,3539.583333,1560
997,31.0,120531.000000,46929,733,147220.82,4,India,Male,Stay,267751.820000,36.0,10044.250000,1466
998,21.0,33661.000000,22314,540,94186.48,5,NaN,Other,Stay,127847.480000,26.0,2805.083333,1080
999,63.0,31930.000000,851,559,100908.40,6,UK,Female,Stay,132838.400000,68.0,2660.833333,1118

10 Random Rows:

,Age,Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,CustomerStatus,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
147,58.0,141704.000000,46445,609,129847.890000,1,USA,Male,Churn,271551.890000,63.0,11808.666667,1218
592,54.0,112458.303158,43715,449,147183.960000,7,UK,Male,Churn,259642.263158,59.0,9371.525263,898
156,18.0,113911.000000,16093,631,3156.220000,4,India,NaN,Churn,117067.220000,23.0,9492.583333,1262
362,29.0,164679.000000,10994,638,111969.790000,7,USA,Female,Stay,276648.790000,34.0,13723.250000,1276
800,54.0,198142.000000,20458,745,143558.240000,5,India,Other,Stay,341700.240000,59.0,16511.833333,1490
931,44.0,70213.000000,18971,475,180332.060000,8,India,Other,Churn,250545.060000,49.0,5851.083333,950
962,31.0,111046.000000,5524,609,100927.910000,4,Canada,Other,Stay,211973.910000,36.0,9253.833333,1218
70,52.0,41122.000000,9568,454,97557.565779,2,France,Male,Churn,138679.565779,57.0,3426.833333,908
735,19.0,180427.000000,40932,573,97557.565779,9,USA,NaN,Stay,277984.565779,24.0,15035.583333,1146
916,21.0,58308.000000,21450,772,175663.450000,2,UK,Male,Stay,233971.450000,26.0,4859.000000,1544

Statistical Summary:

,Age,Income,Spending,Credit_Score,Balance,Tenure,TotalMoney,AgeAfter5Years,MonthlyIncome,CreditScoreDouble
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,44.202000,112458.303158,25285.558000,603.088000,97557.565779,5.241000,210015.868937,49.202000,9371.525263,1206.176000
std,15.130834,51081.475249,14211.735656,176.605486,54430.062006,3.179155,73151.159221,15.130834,4256.789604,353.210972
min,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000,33432.390000,23.000000,1685.583333,600.000000
25%,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000,156611.867500,36.000000,5703.104167,882.000000
50%,44.000000,112458.303158,24901.000000,606.500000,97557.565779,5.000000,210015.868937,49.000000,9371.525263,1213.000000
75%,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000,263542.793945,62.000000,12964.229167,1516.500000
max,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000,390628.400000,75.000000,16663.916667,1800.000000

Target Counts:

CustomerStatus
Churn    506
Stay     494
Name: count, dtype: int64

Final Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   float64
 1   Income             1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   Credit_Score       1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Geography          950 non-null    str
 7   Gender             950 non-null    str
 8   CustomerStatus     1000 non-null   str
 9   TotalMoney         1000 non-null   float64
 10  AgeAfter5Years     1000 non-null   float64
 11  MonthlyIncome      1000 non-null   float64
 12  CreditScoreDouble  1000 non-null   int64
dtypes: float64(6), int64(4), str(3)
memory usage: 101.7 KB